### ISSUE TITLE
[BUG] Value too long and cause the SQLException

### ISSUE THREAD

**Issue by 164ebr** [Ghost-chu/QuickShop-Hikari#1081]
### Description

Two questions
1. Right click on the wooden plaque to display two "owners", with the language file being CN
When creating a store, if you enter a very long number for the price "999999999999999999999999999999999999999", it will cause a database error. It is recommended to determine the size of the entered value here

### Steps to reproduce

no

### Expected Behaviour

fix

### Screenshots

![1111](https://github.com/Ghost-chu/QuickShop-Hikari/assets/86980013/ae8824cb-61da-4c83-8b19-7f40a3d2f1ce)
![BLN)RJR39PV`}M~P6CCQEXE](https://github.com/Ghost-chu/QuickShop-Hikari/assets/86980013/fec3e737-fa18-408d-82f5-4460aae6bd96)

### `/quickshop paste` URL

no

### Additional Context

no

**Comment by YuanYuanOwO** [comment]
First question has been fixed in crowdin

The second question,you can change the price-restriction.yml

**Comment by Ghost-chu** [comment]
I don't think this is a *important* bug, grandstanding on title is counterproductive

**Comment by Ghost-chu** [comment]
Do not report two issues in one Issue, if there are multiple issues to report, please open multiple Issues separately.

**Comment by Ghost-chu** [comment]
Please note that you did not fill in the required information according to the Issue template. Please fill in the required information according to the template next time.

**Comment by Ghost-chu** [comment]
请注意，您的 Issue 存在多个问题，在下一次汇报时请予以改正，否则您的 Issue 可能会被标记为*不予处理*。

- 请不要在标题中哗众取宠。将其描述的非常重要并不会提高问题处理的优先级。开发者和协作者总是会按照该问题的实际优先级进行处理。您的行为显然正干扰我们的工作。
- Issue 模板未被按照要求填写。对于复现步骤、期待行为以及至关重要的 Paste 链接应被完整和准确的填写。复现步骤有利于我们高效重复问题，寻找出现问题的代码段；期待行为能够让我们了解您是否正误解正常行为：Paste 链接包含了重要的插件内部工作信息，我们十分依赖这些信息进行错误调试。如果您没有按照要求填写模板，开发者和协作者将会在没有任何回复的情况下关闭和确定你的 Issue。

回到 Issue 中所报告的问题：

> Value too long for column

该问题是由于数值超过数据库所最大允许范围导致的，您可以通过调整 `price-restriction.yml` 的 `undefined-max` 对其作出限制。  
在下一版本中，QuickShop-Hikari 将添加对数值范围的额外检查。  

> 两个所有者

这是一个翻译问题，简体中文语言非官方维护语言，该语言的翻译由社区维护，因此难免出现差错。  
在下一版本发布时，将会发布该问题的修正版本，并通过內建 CrowdinOTA 云翻译同步功能更新到所有服务器上。

---

在我们审查您所报告的两个问题后，我们不认为该问题应该被标记为重要（甚至带有两个感叹号），他们都属于“低优先级错误”。
