### ISSUE TITLE
[BUG] Shops in admin claims causing server lockup

### ISSUE THREAD

**Issue by pbanj** [Ghost-chu/QuickShop-Hikari#1178]
### Description

when trying to use a shop in the admin claim it locks up the server. i put the server log as i cant run the paste command because the server locks up. i also noticed it isnt writing anything to the quickshop log.
i have the newest gp, qs, and the gp compat add on. i also tried updating to a new version of protocollib that was made about an hour ago.

using paper 1.20.2
not really sure what the issue is as it was working fine a couple days ago

### Steps to reproduce

- make unlimited shop in an admin claim
- try and buy from it

### Expected Behaviour

allow buying/selling

### Screenshots

nothing to really screenshot

### `/quickshop paste` URL

https://paste.helpch.at/eketuhegiz.php

**Comment by pbanj** [comment]
hmmm doing `/quickshop setowner [quickshop]` on the shops seems tro fix it. not sure what changed to cause it. but i will leave some unfixed in case you want to try and debug anything


shop before the comman
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/17306233/29683a1a-860c-4961-9910-daf20a6816bb)


shop after the command 
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/17306233/49dc3b4f-dfe2-4708-8fed-f10fa216897f)

**Comment by Ghost-chu** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/2311/artifact/compatibility/griefprevention/target/Compat-GriefPrevention-5.2.0.5.jar

Update your griefprevention to latest snapshot and see if problem still persist, it should fixed in snapshot now.
