### ISSUE TITLE
When plugin is reloaded the ongoing fees are taken again

### ISSUE THREAD

**Issue by nnnarvaez** [Ghost-chu/QuickShop-Hikari#1280]
### Description

People where complaining they money was dissapearing, it turned out only people with shops was affected. 
on server restart or plugin reload the ongoing fee is taken everytime and the counter is reset. 

### Steps to reproduce

charge ongoing fees.
create a few shops
use /qs reload or restart the server

money is taken again and again and again

### Expected Behaviour

money taken only once the time is right ?

### Screenshots

none

### `/quickshop paste` URL

https://paste.bin

### Additional Context

lorem

**Comment by Ghost-chu** [comment]
If you restart the server, OngoingFee will recollect it, by design (it's based on the game tick and Bukkit scheduler).
But reloading plugins should not be recharged.
