### ISSUE TITLE
[BUG] Error: Economy system not loaded

### ISSUE THREAD

**Issue by Jannik44** [Ghost-chu/QuickShop-Hikari#1303]
### Description

Fresh new install, installed vault, luckperms, xconomy, protocollib and towny and that error pops up when i try to create a chestshop with the command, if i just sneak and right clock nothing happens at all, what am i doing wrong? also no errors in the logs depite an error in chat being shown, that shouldnt be like that

### Steps to reproduce

![grafik](https://github.com/Ghost-chu/QuickShop-Hikari/assets/76906033/6344ddad-e3fc-41a0-b73e-247f9047ded2)

### Expected Behaviour

its normal thing

### Screenshots

![grafik](https://github.com/Ghost-chu/QuickShop-Hikari/assets/76906033/6814bd0b-ffc7-466b-8676-b929407de296)

### `/quickshop paste` URL

-

**Comment by Ghost-chu** [comment]
Vault is a bridge not a economy plugin. It won't provide you economy feature like a magic, you must properly install a economy plugin.

Installation document: 
https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/setup/install

**Comment by Jannik44** [comment]
> Vault is a bridge not a economy plugin. It won't provide you economy feature like a magic, you must properly install a economy plugin.
> 
> Installation document: https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/setup/install

yes, sure, thats why i also put Xconomy there witch should be the missing economy plugin, its also mentioned on the website, i read the installation manual

**Comment by Ghost-chu** [comment]
XConomy didn't work at all on ypur server, there no XConomy's data directory generated, check the server startup logs, fix any errors or contact XConomy developer.

**Comment by Jannik44** [comment]
> XConomy didn't work at all on ypur server, there no XConomy's data directory generated, check the server startup logs, fix any errors or contact XConomy developer.

can you recommend an alternative economy plugin?

**Comment by Ghost-chu** [comment]
> > XConomy didn't work at all on ypur server, there no XConomy's data directory generated, check the server startup logs, fix any errors or contact XConomy developer.
> 
> can you recommend an alternative economy plugin?

I can't recommend the plugin that I didn't use, I need to take responsibility for my recommendations.

Therefore, the other option mentioned in the installation documentation, ESSX, is the best and stable alternative (although its not a economy plugin at all but it have a economy feature and works well with Vault).  
https://essentialsx.net/
