### ISSUE TITLE
access_inventory[BUG] 

### ISSUE THREAD

**Issue by Colt44Magnum** [Ghost-chu/QuickShop-Hikari#1313]
### Description

I asked the Administration to add a quickshop-hikari.employee permission given these permissions
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/51977107/60c58461-d20f-4326-892f-31b1a3de4ba4)

When I was trying this out after it was added to the server the players given the employee permission set were still not able to access the inventory 

### Steps to reproduce

/qs permission user set [playername] quickshop-hikari.employee

notifcation is gotten on discord because of the addon
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/51977107/b547dd88-d1d5-446a-9943-0712c7d0a47a)

tried to have player open the chest and was unable to

### Expected Behaviour

/qs permission user set [playername] quickshop-hikari.employee

player tries to open the shop inventory and they succeed at doing so

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/51977107/b693d8d5-be8e-4f0f-90b6-7e9a4218f0e6)

### `/quickshop paste` URL

no access

**Comment by Ghost-chu** [comment]
Cant offer helpful support without paste (after reproduce), so please provide the information as more as you can like screenshots for error messages.

**Comment by CorruptedGreed** [comment]
This is fixed in 5.2.0.11, the server you're attempting this on (mine) is still on 5.2.0.10 so it should be fixed next update 😎
