### ISSUE TITLE
[功能建议] 建议添加对Folia服务端的支持

### ISSUE THREAD

**Issue by Q2297045667** [Ghost-chu/QuickShop-Hikari#1327]
### Description

目前Folia相关的插件和Fork已经非常多了，而且在国外相关的热度也一直非常高
现在或者未来添加对Folia的支持我认为很有必要

### Steps to reproduce

无

### Expected Behaviour

无

### Screenshots

无

### `/quickshop paste` URL

无

**Comment by YuanYuanOwO** [comment]
No plans at this moment
目前没有计划

**Comment by YuanYuanOwO** [comment]
https://github.com/Ghost-chu/QuickShop-Hikari/discussions/964

**Comment by Q2297045667** [comment]
> No plans at this moment 目前没有计划

谢谢回复
