### ISSUE TITLE
[BUG] quickshop.tax permission is not working

### ISSUE THREAD

**Issue by BaiYeLoser** [Ghost-chu/QuickShop-Hikari#1348]
### Description

自5.2.0.12更新至5.2.0.14后，并在bc安装了Compat-BungeeCord-5.2.0.14之后，拥有quickshop.tax权限的玩家无法绕过商店税收，删除bc的Compat-BungeeCord仍然无法恢复，因为服务器玩家较多不能确保退版本是否会出现问题,再次反馈

### Steps to reproduce

购买商品，拥有quickshop.tax的玩家仍然会被扣税,lp检查玩家在这个服也是拥有绕过权限节点的

### Expected Behaviour

检查是否是由更新导致的错误

### Screenshots

![S~CM2 )K4TRMG2GGCVIIF06](https://github.com/Ghost-chu/QuickShop-Hikari/assets/42574120/4675e510-0e40-41ed-96bc-c4980ffe7fdb)

### `/quickshop paste` URL

https://pan.baidu.com/s/1QdIGzP9gHOyxPJNsj6uSIA?pwd=gwd8

**Comment by Ghost-chu** [comment]
请使用 /quickshop debug 启用调试模式后再次复现问题，并尽快创建paste

**Comment by YuanYuanOwO** [comment]
可是 Paste 报告里的是 5.2.0.11 啊？

**Comment by BaiYeLoser** [comment]
> 可是 Paste 报告里的是 5.2.0.11 啊？

xdd????不会吧,我一会儿去试试看

**Comment by YuanYuanOwO** [comment]
> > 可是 Paste 报告里的是 5.2.0.11 啊？
> 
> xdd????不会吧,我一会儿去试试看

![{188B79E4-DC38-4bd5-B3A0-2A8790176F2E}](https://github.com/Ghost-chu/QuickShop-Hikari/assets/81153017/1abb083a-8b08-486f-b4bb-ec1d23f0b1f6)
请尝试更新到最新版本后重试问题是否存在，然后看一下上面重现问题
