### ISSUE TITLE
[BUG] History GUI Broken

### ISSUE THREAD

**Issue by murat716** [Ghost-chu/QuickShop-Hikari#1402]
### Description

QuickShop-Hikari-6.0.0.6.jar
version: 1.20.4
lang: tr

### Steps to reproduce

1. Create a shop
2. Right click sign
3. Click history button
4. You can take items

### Expected Behaviour

Unable to take items

### Screenshots

![resim](https://github.com/Ghost-chu/QuickShop-Hikari/assets/49496860/e07b4c69-fa0d-4d71-94a3-b54518a2aa27)

### `/quickshop paste` URL

-

**Comment by Ghost-chu** [comment]
Cannot reproduce, please test it in a clean server: Only ESSX, Vault and QuickShop-Hikari and see if it working.
