### ISSUE TITLE
[BUG] Behavior when ShopPriceChangeEvent is cancelled

### ISSUE THREAD

**Issue by YKDZ** [Ghost-chu/QuickShop-Hikari#1436]
### Description

When the shop price is reset using the command `/qs price [price]` and the ShopPriceChangeEvent is cancelled, the fee required to change the shop price is still charged and the `Action is canceled. Reason: xxx` message is not displayed.

### Steps to reproduce

1. Use some method to cancel ShopPriceChangeEvent like this Skirpt
![2024-02-28_23-32-44](https://github.com/Ghost-chu/QuickShop-Hikari/assets/69898831/215c0bc6-b33d-42d6-b7d8-aeb74455bfca)
2. Use the command to change the shop price
3. Discover the problem

### Expected Behaviour

Players should not be charged for modifications, and Action cancel prompts should be displayed.

### Screenshots

![2024-02-28_23-46-16](https://github.com/Ghost-chu/QuickShop-Hikari/assets/69898831/76e65ae2-c06d-4257-adf5-f0c78e7c9388)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FDRPZooZTWy

**Comment by YuanYuanOwO** [comment]
check the config.yml
If you want to cancel the shop price charge
```
  # Should there be a fee for changing shop prices?
  # This can help with endless price undercutting.
  price-change-requires-fee: true
  # The amount of this fee.
  fee-for-price-change: 50
```

**Comment by YKDZ** [comment]
I set price-change-requires-fee to false, but the behavior remains unchanged when the event itself is canceled:
![2024-02-29_09-33-43](https://github.com/Ghost-chu/QuickShop-Hikari/assets/69898831/63f04913-1ad3-4714-b1fd-deeb6b68c38b)

**Comment by Ghost-chu** [comment]
This fix involves an API change and will be delayed until the 7.0.0.0 major update.
