### ISSUE TITLE
[BUG] Bug at german translation

### ISSUE THREAD

**Issue by ZuRiKanHD** [Ghost-chu/QuickShop-Hikari#1467]
### Description

The shop owner is spelled “shopeigentümer” in German.
The description is missing for the /qs history command.

### Steps to reproduce

use command /qs

### Expected Behaviour

-

### Screenshots

![Bild_2024-03-17_225901042](https://github.com/Ghost-chu/QuickShop-Hikari/assets/140162095/0a18235f-36d4-4d81-a96e-1ee93272162f)

### `/quickshop paste` URL

-

**Comment by Ghost-chu** [comment]
Sorry but I can't help, if you can speak German, please correct them on Crowdin: 
https://crowdin.com/project/quickshop-hikari

**Comment by YuanYuanOwO** [comment]
`The description is missing for the /qs history command.`
will fix in next release
