### ISSUE TITLE
[BUG] ShopClickEvent and other events cannot be cancelled

### ISSUE THREAD

**Issue by Mirayii** [Ghost-chu/QuickShop-Hikari#1468]
### Description

When trying to Cancel events in QuickShop through API, it doesn't work. Clicking on Shop with the event Cancelled opens the Info Panel/Buy from shop even tho it's cancelled. I checked if the event is called fine and it works. Tried to cancel the event without any if statements and still did not work. Tried deprecated and new methods.

### Steps to reproduce

1. Create custom plugin
2. Create listener where any QuickShop Event is cancelled

### Expected Behaviour

Event should be cancelled (and provide reason if specified).

### Screenshots

Not neccessary

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FaGgugUcMaZ

**Comment by Ghost-chu** [comment]
This API should work as expected, have you registered the listener correctly?
If you want to cancel the info panel, you should listen to ShopInfoPanelEvent and cancel it.

If possible, please provide your full code snippet.

**Comment by Mirayii** [comment]
The Listener is registered correctly since it returns everything when debugging but doesn’t cancel.
Since it’s not documented, will ShopInfoPanelEvent cancel the “Buying/Selling” from the shop? I want to cancel exactly that.

**Comment by Ghost-chu** [comment]
> The Listener is registered correctly since it returns everything when debugging but doesn’t cancel. Since it’s not documented, will ShopInfoPanelEvent cancel the “Buying/Selling” from the shop? I want to cancel exactly that.

Get the shop instance from the event and check the shop type.

**Comment by Ghost-chu** [comment]
> The Listener is registered correctly since it returns everything when debugging but doesn’t cancel. Since it’s not documented, will ShopInfoPanelEvent cancel the “Buying/Selling” from the shop? I want to cancel exactly that.

No, it for open panel.

**Comment by Ghost-chu** [comment]
ShopPrePurchaseEvent and ShopPurchaseEvent is what for cancel the purchase.
PrePurchaseEvent can hide the purchase chat message if you cancel it. And no pre one can show the reason and have better compatibility with 3rd party addons

**Comment by Mirayii** [comment]
ShopPrePurchaseEvent doesn't exist. ShopPurchaseEvent did not work at first on testing environment, but somehow restarting the server was enough.
