### ISSUE TITLE
Sign [BUG] 

### ISSUE THREAD

**Issue by pittaa** [Ghost-chu/QuickShop-Hikari#1474]
### Description

When i create shop with empty sign next to it, it will make the shop on that sign too.

### Steps to reproduce

Place chest and empty sign next to it.
Then use /qs create on chest.

### Expected Behaviour

Create shop only on chest sign.

### Screenshots

https://github.com/Ghost-chu/QuickShop-Hikari/assets/86187381/922ed396-23a5-4a06-aa2b-86b89587ff92

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHCzQUSPHx1

**Comment by Ghost-chu** [comment]
not a bug,it's feature

write something on sign to prevrnt quickshop convert it
