### ISSUE TITLE
[BUG] ConversationFacotry, Chat Input not getting cleared after ended input.

### ISSUE THREAD

**Issue by akcelerat0r** [Ghost-chu/QuickShop-Hikari#1500]
### Description

Hey, I'm a Developer wondering why my users cant stop the conversation when they buy something...
I also have this bug on one of my Plugins and thought about asking here if this plugin is working with ConversationFactorys.
If yes, I thougt about the soloutions finishing the Conversation with and listener which you can add to the Factory Builder...

### Steps to reproduce

Hey, I'm a Developer wondering why my users cant stop the conversation when they buy something...
I also have this bug on one of my Plugins and thought about asking here if this plugin is working with ConversationFactorys.
If yes, I thougt about the soloutions finishing the Conversation with and listener which you can add to the Factory Builder...

### Expected Behaviour

Add a listener to the ConversationFactory.

### Screenshots

![Screenshot 2024-04-04 220633](https://github.com/Ghost-chu/QuickShop-Hikari/assets/73002105/bcbef325-16d8-41be-833f-0df36c01427c)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FIkWeQ7Dmb4

**Comment by Ghost-chu** [comment]
I've never use conversation API. QuickShop only listen AsyncChatEvent and cancel it when needed.

**Comment by akcelerat0r** [comment]
Okey then, I pay 1 dollar and use anorher buy with the same amount it gets cancelled by the event.
