### ISSUE TITLE
[BUG] /qs toggledisplay not working.

### ISSUE THREAD

**Issue by Castiella** [Ghost-chu/QuickShop-Hikari#1507]
### Description

When /qs toggledisplay is ran, or clicked in the shop chat editor, the hologram item despawns, then re-appears again within secs. (Even though its turned off)

### Steps to reproduce

run /qs toggledisplay or click in the shop chat editor

### Expected Behaviour

the hologram should not re-appear?

### Screenshots

Not sure if necessary 

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FhoWK8kizRg

**Comment by YuanYuanOwO** [comment]
solved in discord support channel  
fix in next version
