### ISSUE TITLE
[BUG] Cannot use virtual item display in version 1.20.4

### ISSUE THREAD

**Issue by Steve29794** [Ghost-chu/QuickShop-Hikari#1516]
### Description

Just like in the picture, whenever I turn on the virtual item display, it always turns off. I installed ProtocolLib and tried other servers, but it still didn't work out

### Steps to reproduce

1. Start your 1.20.4 server
2. If you set the virtual item display, the problem will appear

### Expected Behaviour

Work properly instead of reporting errors

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/88417604/fe656fac-80dc-4527-9c26-c4bd6de65464)

### `/quickshop paste` URL

https://paste.helpch.at/tipitezigi

**Comment by YuanYuanOwO** [comment]
It's QuickShop-Reremake
not the QuickShop-Hikari

**Comment by Ghost-chu** [comment]
QuickShop-Reremake not our product.

**Comment by Steve29794** [comment]
> QuickShop-Reremake not our product.

I'm very sorry that I made a mistake, I installed the wrong plugin, please help me delete this issue

**Comment by YuanYuanOwO** [comment]
> > QuickShop-Reremake not our product.
> 
> I'm very sorry that I made a mistake, I installed the wrong plugin, please help me delete this issue

that's okay,you can join our discord server.

**Comment by Ghost-chu** [comment]
> > QuickShop-Reremake not our product.
> 
> I'm very sorry that I made a mistake, I installed the wrong plugin, please help me delete this issue

This Issue has been closed and will no longer be displayed on the Issue Tracker. Issues are not deleted unless they contain information that must be deleted.

**Comment by Steve29794** [comment]
> > > QuickShop-Reremake not our product.
> > 
> > 
> > I'm very sorry that I made a mistake, I installed the wrong plugin, please help me delete this issue
> 
> This Issue has been closed and will no longer be displayed on the Issue Tracker. Issues are not deleted unless they contain information that must be deleted.

Ok thanks
