### ISSUE TITLE
[BUG] Can take head of history

### ISSUE THREAD

**Issue by kaztti** [Ghost-chu/QuickShop-Hikari#1522]
### Description

The more “purchase history,” the easier it is to get heads.

### Steps to reproduce

1.Open history
2.take the head

### Expected Behaviour

 Speed up the loading of the “Purchase History.

### Screenshots

https://github.com/Ghost-chu/QuickShop-Hikari/assets/137495022/708c3eaa-5845-4dc0-83e4-73acfa4a001b

### `/quickshop paste` URL

a

**Comment by Ghost-chu** [comment]
This is a known issue if other plug-ins modify InventoryGUI items. The listener will immediately become invalid and the GUI protection will be lost.
