### ISSUE TITLE
[BUG] 在我更新了6.1.0.2后它仍然向我推送6.1.0.1

### ISSUE THREAD

**Issue by yxc0915** [Ghost-chu/QuickShop-Hikari#1527]
### Description

在我更新了6.1.0.2后它仍然向我推送6.1.0.1
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/62410385/4ded5668-8431-47c4-88c7-cef8f3efadef)

### Steps to reproduce

等待quickshop的更新推送

### Expected Behaviour

不应该推送旧的版本

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/62410385/6a0cfa24-3726-4d6d-9f07-4784a77d02b6)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FugLDsyZq5O

**Comment by YuanYuanOwO** [comment]
![Image_1714356986223.jpg](https://github.com/Ghost-chu/QuickShop-Hikari/assets/81153017/fc3d07ba-9859-454b-add4-06b02d3b7d1b)

是已知问题
