### ISSUE TITLE
[BUG] Doublechest shop

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Ghost-chu/QuickShop-Hikari#1549]
### Description

Hello , I recently switched from Reremake to this plugin. (https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/addon/reremake-migrator)

However, today I ran into a problem where the player creates a shop on a large chest. The chest is full and when created and the quantity agrees. As he leaves the site, for example on /spawn and puts /back, when he clicks the quantity is only from 1/2 of the chest. I don't know where the problem could be, I tried destroying the chest, creating the shop again but it still happens.

### Steps to reproduce

Just leave the place with the shop, for example via /spawn and put /back. When he clicks on the quantity, there is only 1/2 the quantity

### Expected Behaviour

Is it possible to advise me where the error might be or how to fix it?

### Screenshots

https://github.com/Ghost-chu/QuickShop-Hikari/assets/68572049/c35f649e-5649-499a-af4d-8a8b3024d566

### `/quickshop paste` URL

https://paste.helpch.at/raw/vahapuqeqi

**Comment by Ghost-chu** [comment]
This is a known issue. Unfortunately over the past two years I have been unable to find a specific cause for this issue.
Also, you apparently need to provide the Paste URL instead of the Console Logs

**Comment by Ghost-chu** [comment]
I have known about this issue for some time, unfortunately I have never been able to reproduce it in a test server.

**Comment by Ghost-chu** [comment]
fixed
