### ISSUE TITLE
Display of placeholders on a sign

### ISSUE THREAD

**Issue by Kaeternn** [Ghost-chu/QuickShop-Hikari#1571]
### Description

When the name of my currency is set in a economy plugin as a placeholder configured in ItemAdders.

### Steps to reproduce

1. Via a economy plugin, change your currency name by a ItemAdders emoji placeholder
2. Create a shop
3. Notice that the placeholder on the shop sign does not display the emoji, but the placeholder in plain text

### Expected Behaviour

QuickShop should display the emoji (like it does in all of chat messages) on the sign instead of the plain text placeholder.

FYI, ItemAdders does allow people to put emojis on sign.

### What I got
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/73291571/6fb5fdea-4948-45c6-9fc3-f92a49e20722)

### What I want
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/73291571/20acd973-5cf1-41fd-8ef7-965542e52f29)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FVbH5pqaZyn

### Additional Context

Here is the placeholder working in a chat message generated by QuickShop

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/73291571/106a2950-3b81-45e9-a180-6289590615d3)

**Comment by Ghost-chu** [comment]
QuickShop never handles these placeholders. The currency symbols come from your Economy plugin and are displayed as is.

**Comment by Kaeternn** [comment]
> QuickShop never handles these placeholders. The currency symbols come from your Economy plugin and are displayed as is.

I see, is it planified to make QS handle placeholders on signs ? That would be really cool

**Comment by Ghost-chu** [comment]
> > QuickShop never handles these placeholders. The currency symbols come from your Economy plugin and are displayed as is.
> 
> I see, is it planified to make QS handle placeholders on signs ? That would be really cool

As I said, QuickShop is displaying the currency symbols as is, which works as expected.
If it's not being replaced, try contacting ItemAdder to add a filter for Sign packets.

**Comment by creatorfromhell** [comment]
Not planned.
