### ISSUE TITLE
[BUG] Can't download libraries

### ISSUE THREAD

**Issue by ghost** [Ghost-chu/QuickShop-Hikari#159]
### Description

when i update quickshop and restart the server, it cannot download the newest libraries
i try another server, still doesn't work
server core: [Mirai](https://github.com/etil2jz/Mirai) (a pufferfish/paper fork)

### Steps to reproduce

1. Add/Update Quickshop (version 1.1.3.5)
2. Restart the server
3. Download libraries failed

### Expected Behaviour

Quickshop should load normally

### Screenshots

check pastebin
errors in console

### `/qs paste` URL

https://pastebin.com/ZZ7tV2qP

**Comment by Ghost-chu** [comment]
Your host cannot verify the [Maven central](https://repo1.maven.org/maven2/) SSL certificate.

QuickShop cannot fix this issue as the dependency resolution and download is done by the server core.

Please try updating the SSL certificate repository on your operating system or Java installation.

https://ao.ms/solved-pkix-path-building-failed-unable-to-find-valid-certification-path-to-requested-target/

I believe this issue also affects other plugins that use dependency resolver, and should also report to Mirai/Pufferfish/Paper.
