### ISSUE TITLE
[BUG] dupping item 

### ISSUE THREAD

**Issue by mathemaciel** [Ghost-chu/QuickShop-Hikari#1596]
### Description

When the player creates the store and another player goes to buy, when clicking on the sign with the left button it generates an item with a totally strange description, generating several items, at no cost

### Steps to reproduce

1 create store
2 player click to buy 
3 item dupping genereted ...

### Expected Behaviour

remove this bug at the time of purchase

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/68457323/2f82b4b0-ae02-4c37-a9db-bd850f126425)
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/68457323/7064fcff-4259-4099-a644-3a87f4a1f1ae)
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/68457323/30cc6598-8626-48b5-b23d-3505a7f93655)
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/68457323/f28a99be-3f0c-4a83-89f1-4bc009f8bc7f)

### `/quickshop paste` URL

https://paste.helpch.at/caqazezano

**Comment by Ghost-chu** [comment]
You are using QuickShop-Reremake instead of QuickShop-Hikari and you are reporting to the wrong place. I will close this Issue.

**Comment by YuanYuanOwO** [comment]
You are not using **QuickShop-Hikari**
You are running QuickShop-Reremake
，you need to set display-type to 2
