### ISSUE TITLE
[BUG]  Tax message incorrect in German translation

### ISSUE THREAD

**Issue by ZuRiKanHD** [Ghost-chu/QuickShop-Hikari#1599]
### Description

Good day,

I have discovered the following problem. We use the plugin for our 1.20.4 Paper AND Pufferfish servers. On our server we have set the tax to 0.00%. Now we have the problem that in a purchase message the variable for the amount of tax is not displayed, or is "0". It would be desirable to be able to switch off the taxes so that taxes are not mentioned at all in the purchase message to the seller.

### Steps to reproduce

1. Set the tax to 0.00
2. Buy something from a quick shop

### Expected Behaviour

 It would be desirable to be able to switch off the taxes so that taxes are not mentioned at all in the purchase message to the seller.

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/140162095/ace460e1-2407-4c24-8623-538dab3db11b)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FwtKHhnnKKA

### Additional Context

"I confirm that I have not read these checkboxes and therefore I just ticked them all. "

Of course I have read it, but I can only create this ticket if I tick the box.

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by Ghost-chu** [comment]
Welcome to the QuickShop-Hikari community.

This issue has been fixed, please run `/quickshop reload` to allow QuickShop-Hikari to connect to the translation update server and update the language files.

**Comment by Ghost-chu** [comment]
Thanks for reporting the bug feedback template issue, which was fixed.
