### ISSUE TITLE
[BUG] Unable to load food components correctly when restart the server

### ISSUE THREAD

**Issue by StarOnWater** [Ghost-chu/QuickShop-Hikari#1622]
### Description

After restarting the server, the items purchased in the store cannot be eaten

### Steps to reproduce

1. Listing items with food components
2. Buy items, food components are working properly
3. Restart the server
4. Buy again, items lost food components

### Expected Behaviour

Just fix it!

### Screenshots

Before restart the server:
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/129726122/2e2d4458-b8fd-4383-aaf9-5e03f60fcca1)
After restart the server:
![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/129726122/16ff0349-d0e6-48f1-901a-d81cb7ddc7c5)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FUfFfEe9IFc

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by Ghost-chu** [comment]
感谢您报告此问题。QuickShop 不会对物品进行任何额外修改，因此该问题看起来似乎是 Spigot 的一个物品序列化/反序列化错误。  
由于近期没有空闲时间处理错误报告，Issue 将暂挂，请耐心等待。

**Comment by StarOnWater** [comment]
> 感谢您报告此问题。QuickShop 不会对物品进行任何额外修改，因此该问题看起来似乎是 Spigot 的一个物品序列化/反序列化错误。 由于近期没有空闲时间处理错误报告，Issue 将暂挂，请耐心等待。

豪德，谢谢

**Comment by creatorfromhell** [comment]
> > 感谢您报告此问题。QuickShop 不会对物品进行任何额外修改，因此该问题看起来似乎是 Spigot 的一个物品序列化/反序列化错误。 由于近期没有空闲时间处理错误报告，Issue 将暂挂，请耐心等待。
> 
> 豪德，谢谢

Looks like they have made an API for this in Spigot, as of their 1.21 builds, could you validate?
