### ISSUE TITLE
[BUG] Trapdoors remove display item

### ISSUE THREAD

**Issue by Cats1337** [Ghost-chu/QuickShop-Hikari#1626]
### Description

If you place a trapdoor on top of a chest the display item will be removed after a restart.

### Steps to reproduce

1. Create a shop chest
2. Have display item
3. Place a trapdoor above the chest
4. Restart Server
5. ???
6. loss

### Expected Behaviour

The display item should still appear, the block is not solid, not does it obstruct it.
Trapdoors, and maybe glass? Should be checked and considered as an 'air' block so that the display item spawns.

### Screenshots

![image](https://github.com/QuickShop-Community/QuickShop-Hikari/assets/42129397/ddaba798-68c9-44b7-aade-b5009776aa18)

### `/quickshop paste` URL

https://paste.helpch.at/bivikatare.php

### Additional Context

Using PurPur, Geyser is installed, there shouldn't be any issue with other plugins.
1.21
QuickShop version 6.2.0.5

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [X] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
i am pretty sure it's a realdisplayitem bug  (maybe)
could you try switch to Virtual DisplayItem?  
https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/modules/shops/display-system#virtual-displayitem

**Comment by Cats1337** [comment]
> i am pretty sure it's a realdisplayitem bug (maybe) could you try switch to Virtual DisplayItem? https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/modules/shops/display-system#virtual-displayitem

Already using Virtual DisplayItem

```# Should we place display items on the chests?
  # This may cause duped items, especially for modded servers if you're using Real DisplayItem!
  display-items: true
  
  # QuickShop will check if the display item is in a valid position every specified amount of ticks.
  # Set to 0 to disable it.
  # It doesn't work under Virtual DisplayItem.
  display-items-check-ticks: 6000
  
  # The display type you want use.
  # Old mode, ArmorStand (display-type=1) is Outdated and could not be used
  # 0=Normal Dropped Item
  # 2=Virtual Item (Requires ProtocolLib, fallback to type 0 if ProtocolLib is not installed)
  display-type: 2
  
  # Allow QuickShop to automatically despawn displays when no players are in range of the shop.
  display-auto-despawn: false
  
  # The range at which displays will despawn.
  display-despawn-range: 10
  
  # The interval (in ticks) at which QS checks the shops range to despawn/spawn displays.
  # It doesn't work under Virtual DisplayItem.
  display-check-time: 40
  
  # Allow displays to show stack effects when stack creation is turned on.
  # It doesn't work under Virtual DisplayItem.
  display-allow-stacks: true```

**Comment by YuanYuanOwO** [comment]
> > i am pretty sure it's a realdisplayitem bug (maybe) could you try switch to Virtual DisplayItem? https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/modules/shops/display-system#virtual-displayitem
> 
> Already using Virtual DisplayItem
> 
> ```
>   # This may cause duped items, especially for modded servers if you're using Real DisplayItem!
>   display-items: true
>   
>   # QuickShop will check if the display item is in a valid position every specified amount of ticks.
>   # Set to 0 to disable it.
>   # It doesn't work under Virtual DisplayItem.
>   display-items-check-ticks: 6000
>   
>   # The display type you want use.
>   # Old mode, ArmorStand (display-type=1) is Outdated and could not be used
>   # 0=Normal Dropped Item
>   # 2=Virtual Item (Requires ProtocolLib, fallback to type 0 if ProtocolLib is not installed)
>   display-type: 2
>   
>   # Allow QuickShop to automatically despawn displays when no players are in range of the shop.
>   display-auto-despawn: false
>   
>   # The range at which displays will despawn.
>   display-despawn-range: 10
>   
>   # The interval (in ticks) at which QS checks the shops range to despawn/spawn displays.
>   # It doesn't work under Virtual DisplayItem.
>   display-check-time: 40
>   
>   # Allow displays to show stack effects when stack creation is turned on.
>   # It doesn't work under Virtual DisplayItem.
>   display-allow-stacks: true```
> ```
can't reproduce it with virtual display item  
please upload the paste report.

**Comment by Cats1337** [comment]
Doing /qs paste just gives me a "paste-warning-plugin-find"

**Comment by YuanYuanOwO** [comment]
> Doing /qs paste just gives me a "paste-warning-plugin-find"

You need to uninstall ConsoleSpamFix/ConsoleFilter/LogFilter  
Then use paste feature.

**Comment by Cats1337** [comment]
```
[22:06:44 WARN]: [QuickShop-Hikari] Failed to initialize the virtual display item, try update your ProtocolLib to latest dev build and make sure QuickShop-Hikari up-to-date.
java.lang.IllegalStateException: Unsupported Virtual Display Minecraft version: v1_21_R1
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.load(VirtualDisplayItemManager.java:63) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.<init>(VirtualDisplayItemManager.java:40) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.loadVirtualDisplayItem(QuickShop.java:705) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.onEnable(QuickShop.java:599) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShopBukkit.onEnable(QuickShopBukkit.java:102) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:06:44 WARN]: [QuickShop-Hikari] Failed to process virtual display item system
java.lang.IllegalStateException: Unsupported Virtual Display Minecraft version: v1_21_R1
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.load(VirtualDisplayItemManager.java:63) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.<init>(VirtualDisplayItemManager.java:40) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.loadVirtualDisplayItem(QuickShop.java:705) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.onEnable(QuickShop.java:599) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShopBukkit.onEnable(QuickShopBukkit.java:102) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

ProtocolLib is v5.3.0-Snapshot-723...

**Comment by creatorfromhell** [comment]
> ```
> [22:06:44 WARN]: [QuickShop-Hikari] Failed to initialize the virtual display item, try update your ProtocolLib to latest dev build and make sure QuickShop-Hikari up-to-date.
> java.lang.IllegalStateException: Unsupported Virtual Display Minecraft version: v1_21_R1
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.load(VirtualDisplayItemManager.java:63) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.<init>(VirtualDisplayItemManager.java:40) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.loadVirtualDisplayItem(QuickShop.java:705) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.onEnable(QuickShop.java:599) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShopBukkit.onEnable(QuickShopBukkit.java:102) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> [22:06:44 WARN]: [QuickShop-Hikari] Failed to process virtual display item system
> java.lang.IllegalStateException: Unsupported Virtual Display Minecraft version: v1_21_R1
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.load(VirtualDisplayItemManager.java:63) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.shop.display.virtual.VirtualDisplayItemManager.<init>(VirtualDisplayItemManager.java:40) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.loadVirtualDisplayItem(QuickShop.java:705) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShop.onEnable(QuickShop.java:599) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at QuickShop-Hikari-6.2.0.5.jar/com.ghostchu.quickshop.QuickShopBukkit.onEnable(QuickShopBukkit.java:102) ~[QuickShop-Hikari-6.2.0.5.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
>         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```
> 
> ProtocolLib is v5.3.0-Snapshot-723...

Are you using the snapshot build or modrinth/spigot release?

**Comment by Cats1337** [comment]
> Are you using the snapshot build or modrinth/spigot release?

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Cats1337** [comment]
I'm not sure if this is a related issue to ProtocolLib, but /shop history GUI doesn't work correctly... Players can just take items out of...

**Comment by YuanYuanOwO** [comment]
> I'm not sure if this is a related issue to ProtocolLib, but /shop history GUI doesn't work correctly... Players can just take items out of...

Update your QuickShop to dev build
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/3079/artifact/quickshop-bukkit/target/

**Comment by Cats1337** [comment]
![image](https://github.com/user-attachments/assets/5500a13b-6ff8-4531-8f58-a82d442975f2)
Display Items are now showing 3 items instead of 1, removing the shop keeps the 2 other items
I have updated to most recent release

**Comment by Cats1337** [comment]
> ![image](https://private-user-images.githubusercontent.com/42129397/348942733-5500a13b-6ff8-4531-8f58-a82d442975f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTUwNTEsIm5iZiI6MTcyMTE1NDc1MSwicGF0aCI6Ii80MjEyOTM5Ny8zNDg5NDI3MzMtNTUwMGExM2ItNmZmOC00NTMxLThmNTgtYTgyZDQ0Mjk3NWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE4MzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDJjODNkZTZmYTE5NGMyNzJhODk4OGEzOGRhYzFkNTZiMTI1ZjM2OGFlN2E1YjdmNjgwYTgyYzFlOGNlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFcxygHFONkWtPfzfYOATZFWOMTTHdxWCIGRbiOHjAA) Display Items are now showing 3 items instead of 1, removing the shop keeps the 2 other items I have updated to most recent release

![image](https://github.com/user-attachments/assets/9fe865b1-7553-47a4-b276-7f742e5b0c95)

**Comment by creatorfromhell** [comment]
> > ![image](https://private-user-images.githubusercontent.com/42129397/348942733-5500a13b-6ff8-4531-8f58-a82d442975f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTUwNTEsIm5iZiI6MTcyMTE1NDc1MSwicGF0aCI6Ii80MjEyOTM5Ny8zNDg5NDI3MzMtNTUwMGExM2ItNmZmOC00NTMxLThmNTgtYTgyZDQ0Mjk3NWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE4MzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDJjODNkZTZmYTE5NGMyNzJhODk4OGEzOGRhYzFkNTZiMTI1ZjM2OGFlN2E1YjdmNjgwYTgyYzFlOGNlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFcxygHFONkWtPfzfYOATZFWOMTTHdxWCIGRbiOHjAA) Display Items are now showing 3 items instead of 1, removing the shop keeps the 2 other items I have updated to most recent release
> 
> ![image](https://private-user-images.githubusercontent.com/42129397/349232599-9fe865b1-7553-47a4-b276-7f742e5b0c95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODc2NjgsIm5iZiI6MTcyMTc4NzM2OCwicGF0aCI6Ii80MjEyOTM5Ny8zNDkyMzI1OTktOWZlODY1YjEtNzU1My00N2E0LWIyNzYtN2Y3NDJlNWIwYzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAyMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MGQxNTdmODczOGQ3MDU4ZDk3NDI3ZTQ4MTg0NzkyY2ZhNDE0NDdmZTQ0OTE0NTQ0NmMxNGY1OGVjMzdmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9UzPJkDxFfa_oayaaeI01d5LVtNpsCC9cqISW5HiP8)

Check build on github:

![image](https://github.com/user-attachments/assets/677b74b9-4d55-4c83-aae8-aab0d2571439)


Also, the essentials command of /killall drops seems to work for me in terms of getting rid of duped items.
