### ISSUE TITLE
[BUG] FabledSkyblock integration

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Ghost-chu/QuickShop-Hikari#1631]
### Description

Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin.
I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.

Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. 
Thank you very much

### Steps to reproduce

Anyone can set up shop on a foreign island

### Expected Behaviour

Old Reremake Config:

#FabledSkyblock Integration
fabledskyblock:
# If a player wants to create a shop, the player must have the quickshop-create flag.
# If a player wants to trade a shop, the player must have the quickshop-trade flag.
enable: true
#Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area?
whitelist-mode: false
create:
- MEMBER
- OWNER
- OPERATOR
- COOP

### Screenshots

![image](https://github.com/QuickShop-Community/QuickShop-Hikari/assets/68572049/f3cfad64-4763-4eeb-a085-4353ca9ca123)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
> ### Description
> Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin. I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.
> 
> Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. Thank you very much
> 
> ### Steps to reproduce
> Anyone can set up shop on a foreign island
> 
> ### Expected Behaviour
> Old Reremake Config:
> 
> #FabledSkyblock Integration fabledskyblock:
> 
> # If a player wants to create a shop, the player must have the quickshop-create flag.
> # If a player wants to trade a shop, the player must have the quickshop-trade flag.
> enable: true #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area? whitelist-mode: false create:
> 
> * MEMBER
> * OWNER
> * OPERATOR
> * COOP
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/68572049/345590734-f3cfad64-4763-4eeb-a085-4353ca9ca123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjgxMTgsIm5iZiI6MTcyMDU2NzgxOCwicGF0aCI6Ii82ODU3MjA0OS8zNDU1OTA3MzQtZjNjZmFkNjQtNDc2My00ZWViLWEwODUtNDM1M2NhOWNhMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjA1ZWU0OTNmMTk0MDg5ZDg1MDFmNGI4YWM1N2JhNjBkZmJjMWM2NTI2MThhNjlmZDU2YTYxMWQ0MjljOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qayZHqKT972Z8Nn3Ytm7yBFh_5mxTrHLyflHnYs8SKk)
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [x]  I'm running Paper or Spigot, and not a fork
> * [x]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

Link to plugin?

**Comment by Sh3r1ffCZ** [comment]
> > ### Description
> > Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin. I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.
> > Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. Thank you very much
> > ### Steps to reproduce
> > Anyone can set up shop on a foreign island
> > ### Expected Behaviour
> > Old Reremake Config:
> > #FabledSkyblock Integration fabledskyblock:
> > # If a player wants to create a shop, the player must have the quickshop-create flag.
> > # If a player wants to trade a shop, the player must have the quickshop-trade flag.
> > enable: true #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area? whitelist-mode: false create:
> > 
> > * MEMBER
> > * OWNER
> > * OPERATOR
> > * COOP
> > 
> > ### Screenshots
> > ![image](https://private-user-images.githubusercontent.com/68572049/345590734-f3cfad64-4763-4eeb-a085-4353ca9ca123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjgxMTgsIm5iZiI6MTcyMDU2NzgxOCwicGF0aCI6Ii82ODU3MjA0OS8zNDU1OTA3MzQtZjNjZmFkNjQtNDc2My00ZWViLWEwODUtNDM1M2NhOWNhMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjA1ZWU0OTNmMTk0MDg5ZDg1MDFmNGI4YWM1N2JhNjBkZmJjMWM2NTI2MThhNjlmZDU2YTYxMWQ0MjljOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qayZHqKT972Z8Nn3Ytm7yBFh_5mxTrHLyflHnYs8SKk)
> > ### `/quickshop paste` URL
> > https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd
> > ### Additional Context
> > _No response_
> > ### Checklist
> > 
> > * [x]   I'm running Paper or Spigot, and not a fork
> > * [x]   I confirm that Paper/Spigot has been updated to the latest build
> > * [x]   I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> > * [ ]   I confirm that I have not read these checkboxes and therefore I just ticked them all.
> > * [x]   I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> > * [x]   I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> > * [x]   I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.
> 
> Link to plugin?

Old plugin:
https://www.spigotmc.org/resources/quickshop-reremake-1-20-2-ready-multi-currency.62575/

Plugin I switched to:
https://www.spigotmc.org/resources/quickshop-hikari-a-powerful-user-friendly-and-relieable-chestshop-plugin-1-18-2-1-21.100125/

**Comment by creatorfromhell** [comment]
> > > ### Description
> > > Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin. I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.
> > > Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. Thank you very much
> > > ### Steps to reproduce
> > > Anyone can set up shop on a foreign island
> > > ### Expected Behaviour
> > > Old Reremake Config:
> > > #FabledSkyblock Integration fabledskyblock:
> > > # If a player wants to create a shop, the player must have the quickshop-create flag.
> > > # If a player wants to trade a shop, the player must have the quickshop-trade flag.
> > > enable: true #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area? whitelist-mode: false create:
> > > 
> > > * MEMBER
> > > * OWNER
> > > * OPERATOR
> > > * COOP
> > > 
> > > ### Screenshots
> > > ![image](https://private-user-images.githubusercontent.com/68572049/345590734-f3cfad64-4763-4eeb-a085-4353ca9ca123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjgxMTgsIm5iZiI6MTcyMDU2NzgxOCwicGF0aCI6Ii82ODU3MjA0OS8zNDU1OTA3MzQtZjNjZmFkNjQtNDc2My00ZWViLWEwODUtNDM1M2NhOWNhMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjA1ZWU0OTNmMTk0MDg5ZDg1MDFmNGI4YWM1N2JhNjBkZmJjMWM2NTI2MThhNjlmZDU2YTYxMWQ0MjljOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qayZHqKT972Z8Nn3Ytm7yBFh_5mxTrHLyflHnYs8SKk)
> > > ### `/quickshop paste` URL
> > > https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd
> > > ### Additional Context
> > > _No response_
> > > ### Checklist
> > > 
> > > * [x]    I'm running Paper or Spigot, and not a fork
> > > * [x]    I confirm that Paper/Spigot has been updated to the latest build
> > > * [x]    I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> > > * [ ]    I confirm that I have not read these checkboxes and therefore I just ticked them all.
> > > * [x]    I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> > > * [x]    I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> > > * [x]    I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.
> > 
> > 
> > Link to plugin?
> 
> Old plugin: https://www.spigotmc.org/resources/quickshop-reremake-1-20-2-ready-multi-currency.62575/
> 
> Plugin I switched to: https://www.spigotmc.org/resources/quickshop-hikari-a-powerful-user-friendly-and-relieable-chestshop-plugin-1-18-2-1-21.100125/

I meant for the fabledskyblock?

**Comment by Sh3r1ffCZ** [comment]
> > > > ### Description
> > > > Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin. I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.
> > > > Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. Thank you very much
> > > > ### Steps to reproduce
> > > > Anyone can set up shop on a foreign island
> > > > ### Expected Behaviour
> > > > Old Reremake Config:
> > > > #FabledSkyblock Integration fabledskyblock:
> > > > # If a player wants to create a shop, the player must have the quickshop-create flag.
> > > > # If a player wants to trade a shop, the player must have the quickshop-trade flag.
> > > > enable: true #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area? whitelist-mode: false create:
> > > > 
> > > > * MEMBER
> > > > * OWNER
> > > > * OPERATOR
> > > > * COOP
> > > > 
> > > > ### Screenshots
> > > > ![image](https://private-user-images.githubusercontent.com/68572049/345590734-f3cfad64-4763-4eeb-a085-4353ca9ca123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjgxMTgsIm5iZiI6MTcyMDU2NzgxOCwicGF0aCI6Ii82ODU3MjA0OS8zNDU1OTA3MzQtZjNjZmFkNjQtNDc2My00ZWViLWEwODUtNDM1M2NhOWNhMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjA1ZWU0OTNmMTk0MDg5ZDg1MDFmNGI4YWM1N2JhNjBkZmJjMWM2NTI2MThhNjlmZDU2YTYxMWQ0MjljOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qayZHqKT972Z8Nn3Ytm7yBFh_5mxTrHLyflHnYs8SKk)
> > > > ### `/quickshop paste` URL
> > > > https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd
> > > > ### Additional Context
> > > > _No response_
> > > > ### Checklist
> > > > 
> > > > * [x]     I'm running Paper or Spigot, and not a fork
> > > > * [x]     I confirm that Paper/Spigot has been updated to the latest build
> > > > * [x]     I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> > > > * [ ]     I confirm that I have not read these checkboxes and therefore I just ticked them all.
> > > > * [x]     I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> > > > * [x]     I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> > > > * [x]     I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.
> > > 
> > > 
> > > Link to plugin?
> > 
> > 
> > Old plugin: https://www.spigotmc.org/resources/quickshop-reremake-1-20-2-ready-multi-currency.62575/
> > Plugin I switched to: https://www.spigotmc.org/resources/quickshop-hikari-a-powerful-user-friendly-and-relieable-chestshop-plugin-1-18-2-1-21.100125/
> 
> I meant for the fabledskyblock?

Oh sorry:
https://songoda.com/product/fabledskyblock-13

**Comment by creatorfromhell** [comment]
> > > > > ### Description
> > > > > Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin. I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.
> > > > > Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. Thank you very much
> > > > > ### Steps to reproduce
> > > > > Anyone can set up shop on a foreign island
> > > > > ### Expected Behaviour
> > > > > Old Reremake Config:
> > > > > #FabledSkyblock Integration fabledskyblock:
> > > > > # If a player wants to create a shop, the player must have the quickshop-create flag.
> > > > > # If a player wants to trade a shop, the player must have the quickshop-trade flag.
> > > > > enable: true #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area? whitelist-mode: false create:
> > > > > 
> > > > > * MEMBER
> > > > > * OWNER
> > > > > * OPERATOR
> > > > > * COOP
> > > > > 
> > > > > ### Screenshots
> > > > > ![image](https://private-user-images.githubusercontent.com/68572049/345590734-f3cfad64-4763-4eeb-a085-4353ca9ca123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjgxMTgsIm5iZiI6MTcyMDU2NzgxOCwicGF0aCI6Ii82ODU3MjA0OS8zNDU1OTA3MzQtZjNjZmFkNjQtNDc2My00ZWViLWEwODUtNDM1M2NhOWNhMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjA1ZWU0OTNmMTk0MDg5ZDg1MDFmNGI4YWM1N2JhNjBkZmJjMWM2NTI2MThhNjlmZDU2YTYxMWQ0MjljOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qayZHqKT972Z8Nn3Ytm7yBFh_5mxTrHLyflHnYs8SKk)
> > > > > ### `/quickshop paste` URL
> > > > > https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd
> > > > > ### Additional Context
> > > > > _No response_
> > > > > ### Checklist
> > > > > 
> > > > > * [x]      I'm running Paper or Spigot, and not a fork
> > > > > * [x]      I confirm that Paper/Spigot has been updated to the latest build
> > > > > * [x]      I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> > > > > * [ ]      I confirm that I have not read these checkboxes and therefore I just ticked them all.
> > > > > * [x]      I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> > > > > * [x]      I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> > > > > * [x]      I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.
> > > > 
> > > > 
> > > > Link to plugin?
> > > 
> > > 
> > > Old plugin: https://www.spigotmc.org/resources/quickshop-reremake-1-20-2-ready-multi-currency.62575/
> > > Plugin I switched to: https://www.spigotmc.org/resources/quickshop-hikari-a-powerful-user-friendly-and-relieable-chestshop-plugin-1-18-2-1-21.100125/
> > 
> > 
> > I meant for the fabledskyblock?
> 
> Oh sorry: https://songoda.com/product/fabledskyblock-13

cheers, so it's the same one that is open source here: https://github.com/craftaro/FabledSkyBlock?tab=readme-ov-file ?

**Comment by Sh3r1ffCZ** [comment]
> > > > > > ### Description
> > > > > > Hello, the reason I marked this as a bug is because "QuickShop-Reremake" had an integration option for the FabledSkyblock plugin. I had to switch to the new shop "QuickShop-Hikari", which unfortunately does not have this. The problem is that players can create shops on foreign islands and then the island owner can't enter them. These "their" shops can also be bought out, so they can actually rob that player as well.
> > > > > > Would it be possible to add the integration that this plugin previously had? I wouldn't want to change the whole Skyblock plugin or shop plugin because of this. Thank you very much
> > > > > > ### Steps to reproduce
> > > > > > Anyone can set up shop on a foreign island
> > > > > > ### Expected Behaviour
> > > > > > Old Reremake Config:
> > > > > > #FabledSkyblock Integration fabledskyblock:
> > > > > > # If a player wants to create a shop, the player must have the quickshop-create flag.
> > > > > > # If a player wants to trade a shop, the player must have the quickshop-trade flag.
> > > > > > enable: true #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area? whitelist-mode: false create:
> > > > > > 
> > > > > > * MEMBER
> > > > > > * OWNER
> > > > > > * OPERATOR
> > > > > > * COOP
> > > > > > 
> > > > > > ### Screenshots
> > > > > > ![image](https://private-user-images.githubusercontent.com/68572049/345590734-f3cfad64-4763-4eeb-a085-4353ca9ca123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjgxMTgsIm5iZiI6MTcyMDU2NzgxOCwicGF0aCI6Ii82ODU3MjA0OS8zNDU1OTA3MzQtZjNjZmFkNjQtNDc2My00ZWViLWEwODUtNDM1M2NhOWNhMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjA1ZWU0OTNmMTk0MDg5ZDg1MDFmNGI4YWM1N2JhNjBkZmJjMWM2NTI2MThhNjlmZDU2YTYxMWQ0MjljOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qayZHqKT972Z8Nn3Ytm7yBFh_5mxTrHLyflHnYs8SKk)
> > > > > > ### `/quickshop paste` URL
> > > > > > https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHlyKSkH2bd
> > > > > > ### Additional Context
> > > > > > _No response_
> > > > > > ### Checklist
> > > > > > 
> > > > > > * [x]       I'm running Paper or Spigot, and not a fork
> > > > > > * [x]       I confirm that Paper/Spigot has been updated to the latest build
> > > > > > * [x]       I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> > > > > > * [ ]       I confirm that I have not read these checkboxes and therefore I just ticked them all.
> > > > > > * [x]       I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> > > > > > * [x]       I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> > > > > > * [x]       I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.
> > > > > 
> > > > > 
> > > > > Link to plugin?
> > > > 
> > > > 
> > > > Old plugin: https://www.spigotmc.org/resources/quickshop-reremake-1-20-2-ready-multi-currency.62575/
> > > > Plugin I switched to: https://www.spigotmc.org/resources/quickshop-hikari-a-powerful-user-friendly-and-relieable-chestshop-plugin-1-18-2-1-21.100125/
> > > 
> > > 
> > > I meant for the fabledskyblock?
> > 
> > 
> > Oh sorry: https://songoda.com/product/fabledskyblock-13
> 
> cheers, so it's the same one that is open source here: https://github.com/craftaro/FabledSkyBlock?tab=readme-ov-file ?

Yess

**Comment by creatorfromhell** [comment]
Merged into master issue #1756
