### ISSUE TITLE
[BUG] Price cant be over 9x29

### ISSUE THREAD

**Issue by F-alling** [Ghost-chu/QuickShop-Hikari#1634]
### Description

I tried to create a shop with a price over 99999999999999999999999999999.99 and it bugs out.

### Steps to reproduce

1: Try to create a shop with the price over 99999999999999999999999999999.99
2: death

### Expected Behaviour

work

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https://bytebin.lucko.me/3mZuo9PzqW

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
> ### Description
> I tried to create a shop with a price over 99999999999999999999999999999.99 and it bugs out.
> 
> ### Steps to reproduce
> 1: Try to create a shop with the price over 99999999999999999999999999999.99 2: death
> 
> ### Expected Behaviour
> work
> 
> ### Screenshots
> _No response_
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https://bytebin.lucko.me/3mZuo9PzqW
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [x]  I'm running Paper or Spigot, and not a fork
> * [x]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

That is the max value programmatically for the data value in Quickshop. Will add a message to prevent death though such as "you've reached the max price."

**Comment by creatorfromhell** [comment]
> > ### Description
> > I tried to create a shop with a price over 99999999999999999999999999999.99 and it bugs out.
> > ### Steps to reproduce
> > 1: Try to create a shop with the price over 99999999999999999999999999999.99 2: death
> > ### Expected Behaviour
> > work
> > ### Screenshots
> > _No response_
> > ### `/quickshop paste` URL
> > https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https://bytebin.lucko.me/3mZuo9PzqW
> > ### Additional Context
> > _No response_
> > ### Checklist
> > 
> > * [x]   I'm running Paper or Spigot, and not a fork
> > * [x]   I confirm that Paper/Spigot has been updated to the latest build
> > * [x]   I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> > * [ ]   I confirm that I have not read these checkboxes and therefore I just ticked them all.
> > * [x]   I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> > * [x]   I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> > * [x]   I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.
> 
> That is the max value programmatically for the data value in Quickshop. Will add a message to prevent death though such as "you've reached the max price."

Edit: Ah, you've changed the config, so yeah obviously that's a negative as programmatically that is beyond the max value for the datatype so no message required, just adjust your config as specified by the comments in it.

**Comment by F-alling** [comment]
I have not changed the config at all.

**Comment by F-alling** [comment]
Ok

**Comment by creatorfromhell** [comment]
> Ok

I'll add this to the todo list as a possible future update to raise the max/change the data type.
