### ISSUE TITLE
[BUG] Invisible sign

### ISSUE THREAD

**Issue by daniel-skopek** [Ghost-chu/QuickShop-Hikari#1638]
### Description

This will happen again even after the shop has been recreated. This only happens for specific shops.

### Steps to reproduce

Unforunately I don't know steps to reproduce.

### Expected Behaviour

Sign should be always visible.

### Screenshots

https://imgur.com/a/AL6vMqv

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHmJ8ucVqVw

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [X] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
Will leave this open, but without reproduction steps this issue is dead in the water.

> ### Description
> This will happen again even after the shop has been recreated. This only happens for specific shops.
> 
> ### Steps to reproduce
> Unforunately I don't know steps to reproduce.
> 
> ### Expected Behaviour
> Sign should be always visible.
> 
> ### Screenshots
> https://imgur.com/a/AL6vMqv
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FHmJ8ucVqVw
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [ ]  I'm running Paper or Spigot, and not a fork
> * [ ]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [x]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by daniel-skopek** [comment]
I will ask players when it's happening but I don't think they will know.

**Comment by YuanYuanOwO** [comment]
Not sure but are you using a vanilla client?

**Comment by daniel-skopek** [comment]
I'm using Fabric but players probably use OptiFine

**Comment by creatorfromhell** [comment]
> I'm using Fabric but players probably use OptiFine

You're joining a vanilla server with a fabric client?

**Comment by daniel-skopek** [comment]
I'm joining to the Pufferfish server with a Fabric client (I'm using mods for optimization, no special mods).

**Comment by creatorfromhell** [comment]
I'm going with this is more on the client side of things 🤔
