### ISSUE TITLE
[BUG] Taxes display incorrect

### ISSUE THREAD

**Issue by CuteLittleSky** [Ghost-chu/QuickShop-Hikari#164]
### Description

tax: 0.05
tax-account: CuteLittleSky
show-tax: true
显示税收后支付的税为交易的金额,而且这部分没有收税,但实际上税收账号能收到这笔钱

### Steps to reproduce

正常交易

### Expected Behaviour

Fix

### Screenshots

![image](https://user-images.githubusercontent.com/62592731/166188141-2268b102-d9f4-43b9-bea0-bc0a12580e6e.png)

### `/qs paste` URL

https://paste.helpch.at/pavuhatife

**Comment by Ghost-chu** [comment]
try this snapshot: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/319/

**Comment by CuteLittleSky** [comment]
> try this snapshot: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/319/

构建失败惹

**Comment by YuanYuanOwO** [comment]
> > try this snapshot: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/319/
> 
> 构建失败惹

https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/320/

**Comment by CuteLittleSky** [comment]
> try this snapshot: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/319/

![}M)CE_RZC7E)01VUYW%N M7](https://user-images.githubusercontent.com/62592731/166420595-a54c5234-7ab7-4eaa-98f5-277fcb68f5a7.jpg)
似乎还是有问题..
