### ISSUE TITLE
[BUG] 启动有一则警告，不知道这个要怎么做

### ISSUE THREAD

**Issue by RedCarl** [Ghost-chu/QuickShop-Hikari#1647]
### Description

ProtocolLib 已经是最新的dev版本
https://paste.fastmirror.net/?432cb7dccfe843b2#GyWe3TYVyipphriwH26REM8Az1ATwUhAASxXNNcsdh6N

### Steps to reproduce

启动服务器

### Expected Behaviour

如何解决这个警告

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2F29vmkpRnzG

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [X] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [ ] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/3079/artifact/quickshop-bukkit/target/
使用开发版即可

**Comment by YuanYuanOwO** [comment]
以及下次使用Github Issue上报BUG时，请使用英语，否则Issue可能会被直接关闭。
或者加入 QuickShop Discord频道
