### ISSUE TITLE
[BUG] Smithing Templates, Music Discs use generic name

### ISSUE THREAD

**Issue by codeHusky** [Ghost-chu/QuickShop-Hikari#1657]
### Description

With Reremake, the name of items such as Smithing Templates and Music Discs would reflect their purpose to a buyer (such as the type of disc, name of the template). Now, they only provide the basic info.
![2024-07-16_21 13 48](https://github.com/user-attachments/assets/35cfa86f-1a44-42e1-afdf-4c123a755dc5)

### Steps to reproduce

1. Create a store with a smithing template or music disc
2. Review the text on the sign

### Expected Behaviour

Provide a more detailed short name, such as which trim the template is for, or which disc it is.

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FroZa1s1YAf

### Additional Context

We are running Paper 1.20.2 for compatibility reasons at the moment.

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
Addressed in the fix/general branch.
