### ISSUE TITLE
[BUG] The ./qs history menu allows you to remove diamond in menu.

### ISSUE THREAD

**Issue by DontMessWithDis** [Ghost-chu/QuickShop-Hikari#1673]
### Description

When typing /qs history the diamond for top 5 valuable customers is removeable and sellable.

### Steps to reproduce

install the latest version with protocol lib and vault.
./qs history
Attempt to remove diamond.

### Expected Behaviour

The diamond should stay in the menu.

### Screenshots

![image](https://github.com/user-attachments/assets/79e82d96-25b0-479b-96ac-e97bf325003b)
![image](https://github.com/user-attachments/assets/95c402ce-f378-4555-99a3-55bb5e193a3d)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FXgtFv9Uk6h

### Additional Context

N/A

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
#1632
