### ISSUE TITLE
[BUG] Displayed Item name is always in brackets and white by default

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Hikari#168]
### Description

When you create a shop using a renamed item, will QuickShop display the name inside square brackets (i.e. `[Example]`) and in white by default.

### Steps to reproduce

1. Rename an item
2. Create a shop with renamed item
3. See the item name in a unusual display

### Expected Behaviour

Name color should not be white and the item name shouldn't be surrounded by square brackets.

### Screenshots

![2022-05-03_16 30 50](https://user-images.githubusercontent.com/11576465/166473562-95ff5267-1eb0-4867-928a-cfc863b46757.png)

### `/qs paste` URL

https://paste.helpch.at/cixeyuguzu

**Comment by Ghost-chu** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/30802565/166740251-345cbe6d-743b-40d3-a8d2-9abe1624c79f.png">
It seems the brackets added by Paper stuff.
