### ISSUE TITLE
[BUG] Out of stock shop signs can open sign edit menu

### ISSUE THREAD

**Issue by codeHusky** [Ghost-chu/QuickShop-Hikari#1682]
### Description

Crouching and right-clicking out of stock shop signs can open the sign editor

### Steps to reproduce

1. Get an out of stock shop
2. Crouch
3. Right click the sign

### Expected Behaviour

It doesn't open a menu

### Screenshots

![2024-07-18_18 57 19](https://github.com/user-attachments/assets/4589e8be-60f4-4c73-9f7b-ba13f43b8b8e)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FTpXcoiYS3C

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
This may be expected behaviour and the shop sign cannot change the text  
and i can't reproduce at sometime

**Comment by YuanYuanOwO** [comment]
Adjust the value of SNEAKING_RIGHT_CLICK_SIGN in interaction.yml to TRADE_INTERACTION  
https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/modules/interaction
