### ISSUE TITLE
[BUG] Minecraft Bedrock edition

### ISSUE THREAD

**Issue by VladislavTestV** [Ghost-chu/QuickShop-Hikari#1683]
### Description

Icons falling over shops under the map in Minecraft Bedrock edition

I am attaching 2 videos with this problem.

https://github.com/user-attachments/assets/5b7c462c-c21f-4c61-af09-761a6488950c

https://github.com/user-attachments/assets/faf86b9a-11d6-4d10-99d6-65495f0008f6

### Steps to reproduce

This issue occurs with the Item display format

### Expected Behaviour

Expected that displayed icons would not fall indefinitely when Item display was activated

### Screenshots

https://github.com/user-attachments/assets/5b7c462c-c21f-4c61-af09-761a6488950c

https://github.com/user-attachments/assets/faf86b9a-11d6-4d10-99d6-65495f0008f6

### `/quickshop paste` URL

not 

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [X] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol
Install this addon
