### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SothIvy4690986** [Ghost-chu/QuickShop-Hikari#1694]
### Description

I am running 1.21 paper mc and i am useing the newest version of QuickShop-Hikari, but it does not load the plugin.
Protocall lib isn't working too, so is that a possibility?

### Steps to reproduce

1. Telling me how to fix this would be great :)

### Expected Behaviour

I expected it to work because its a 1.21 plugin

### Screenshots

![image](https://github.com/user-attachments/assets/b6134f50-9d57-42c2-87c9-f6b8f2351494)

![image](https://github.com/user-attachments/assets/dd8b8a7e-25a6-42b1-9ec5-f94fd9184b5d)

![image](https://github.com/user-attachments/assets/b8f64e87-572c-4d03-8429-6bec0ee0ad7a)

### `/quickshop paste` URL

https://paste.helpch.at/latebicuxo.makefile

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [X] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/  
Upgrade your ProtocolLib to dev build.

**Comment by SothIvy4690986** [comment]
thanks i just saw that lol. my bad
