### ISSUE TITLE
[BUG]  Column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by Baktus79** [Ghost-chu/QuickShop-Hikari#1702]
### Description

I am getting an error message in the console when items are buyed from a container. The transaction seems to go through and everything seems fine, except for the error message.

### Steps to reproduce

Just buy an item from a container and the error will be displayed in the console.

### Expected Behaviour

No error message.

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FyZTyTN4Nef

### Additional Context

The error message is:
`[13:38:31 ERROR]: Column count doesn't match value count at row 1`

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
check your server logs file.(latest.log)
need full logs

**Comment by Baktus79** [comment]
There is no more info to give. Thats it. The reason I know its regarding Quickshop is by buying items from the chest, and this one liner shows up in the console.

**Comment by YuanYuanOwO** [comment]
> Column count doesn't match value count at row 1

Please join our Discord support server and upload your server full logs in discord server

**Comment by creatorfromhell** [comment]
No information was provided as requested.

**Comment by Baktus79** [comment]
The information was given at the Discord server, and the error is still not gone.

**Comment by creatorfromhell** [comment]
> The information was given at the Discord server, and the error is still not gone.

I did not see it on the discord, please repost here, and I'll reopen this issue to be looked at, at some point.

**Comment by creatorfromhell** [comment]
Also, did you attempt to recreate the shop you tested with? Did you have a reproduction method that can be used to recreate the error from a fresh install? Did you use the latest dev build and test with it?

**Comment by Baktus79** [comment]
Sorry, I have been really busy lately and I have no time to test at the moment. I'll let you know when I can find some time :)
