### ISSUE TITLE
[BUG] Item name in chat

### ISSUE THREAD

**Issue by YuanYuanOwO** [Ghost-chu/QuickShop-Hikari#1705]
### Description

In the chat, it appears that the item names are in English  
Doesn't change according to the set language, I guess it has something to do with issue  
#1657 

### Steps to reproduce

create Music discs shop  
switch to other language  

### Expected Behaviour

Use the correct name for the item and it should change according to the set language

### Screenshots

![image](https://github.com/user-attachments/assets/e0b5fe0a-7dd3-4c16-97aa-42975520c6ba)
It's supposed to look like this:
![f41fc642-9365-4c87-a417-a078bf45e3b9](https://github.com/user-attachments/assets/ba44561a-6e59-45ec-8e00-06fd5e56b53b)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FannWPCte3X

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
This is something that was modified per a suggestion, but seems like the naming schema was a Mojang issue so just going to undo the change. One of those mojang things.
