### ISSUE TITLE
[BUG] Muted players can't buy items

### ISSUE THREAD

**Issue by rudde0** [Ghost-chu/QuickShop-Hikari#1718]
### Description

I use LiteBans as moderation provider plugin. Player can't enter amount of how much will gonna buy when player is muted.

### Steps to reproduce

1. get muted when using LiteBans
2. try to buy some item from shop (you can't enter the amount from chat)

### Expected Behaviour

QuickShop should has higher priority than LiteBans

### `/quickshop paste` URL

I get "paste-warning-plugin-find" message when I do /quickshop paste

### Additional Context

I tried to toggle the chat related config values but the related values didn't fixed this issue

I'm using Purpur 1.20.4 (final 1.20.4 build)

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
i think it's not quickshop fault.  
but  
left the shop sign then use `/quickshop amount`

**Comment by creatorfromhell** [comment]
> /quickshop amount

What is your configuration for ignore-cancel-chat-event in config.yml?

**Comment by creatorfromhell** [comment]
This is a use-case for the configuration ignore-cancel-chat-event in config.yml

**Comment by rudde0** [comment]
> This is a use-case for the configuration ignore-cancel-chat-event in config.yml

it didn't fix my issue unfortunately

**Comment by creatorfromhell** [comment]
> > This is a use-case for the configuration ignore-cancel-chat-event in config.yml
> 
> it didn't fix my issue unfortunately

After a restart? Because using this I'm not able to reproduce the issue. So it's definitely something on the server end since I'm unable to reproduce it, or you didn't restart after changing.

**Comment by creatorfromhell** [comment]
Also, if it's still an issue, as was stated earlier, then can use the /qs amount command. Probably shouldn't behave in a way to get muted in the first place.
