### ISSUE TITLE
[BUG] Dropped items cleaner from CMI will clean the hover items on Quickshop

### ISSUE THREAD

**Issue by CaesarGalahad** [Ghost-chu/QuickShop-Hikari#1721]
### Description

Dropped items cleaner from CMI will clean the hover items on Quickshop

SERVER INFO
SERVER Version purpur 2287 1.21.1
QuickShoop version 6.2.0.6

### Steps to reproduce

1. run the Dropped items cleaner from CMI
2. the hover items on Quickshop will be cleared

### Expected Behaviour

it should not be cleaned up as a dropped item

### Screenshots

![image](https://github.com/user-attachments/assets/809a79af-ea26-40f1-853e-0c6dd51694ab)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FK3pf7hkwDG

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
> Because QuickShop is not yet compatible with 1.21.1.you can temp disablle display-item
Virtual displayitem function is not available at the moment, please wait for the plugin update.  

因为QuickShop暂未适配1.21.1,可以临时禁用悬浮物功能
虚拟悬浮物功能暂时不可以使用,请等待插件更新

**Comment by YuanYuanOwO** [comment]
[QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/16622572/QuickShop-Hikari-6.2.0.7.zip)

there is a dev version for 1.21.1,add support for virtual display item 1.21.1
这里有个1.21.1用的开发版，添加了对1.21.1的虚拟悬浮物支持

**Comment by creatorfromhell** [comment]
RealDisplayItems are being discontinued, Virtual Display for 1.21.1 test build coming out soon.
