### ISSUE TITLE
[BUG] Item duplication bug

### ISSUE THREAD

**Issue by Non1Free** [Ghost-chu/QuickShop-Hikari#1736]
### Description

Running on a purpur server on 1.21 QuickShop version 6.2.0.5
When I pushed the mine car with a funnel into the store with suspended items, the funnel mine car sucked in the suspended items and the sucked in items were exactly the same as the original items

### Steps to reproduce

1.Prepare two sections of railway tracks, a mining car with a funnel, a chest, and an item that needs to be replicated
2.Create a chest store
3.Place a square at intervals behind the chest and lay rails to tilt towards the chest
3.Place a mining cart with a funnel and push it down to slide it into the chest
4.Open the mining cart with a funnel, and the copied items are inside

### Expected Behaviour

Fix the bug

### `/quickshop paste` URL

I'm just a player,and i cannot execute this command.

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [ ] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
Update your QuickShop to dev build

**Comment by Non1Free** [comment]
thanks
