### ISSUE TITLE
[BUG] Clicking on "View histroy" does nothing, only sends sound (1.18 Purpur)

### ISSUE THREAD

**Issue by TomLewis** [Ghost-chu/QuickShop-Hikari#1740]
### Description

![2024-08-25_14 24 27](https://github.com/user-attachments/assets/2ccceb5c-2f9a-4b06-a35e-066baaed39bd)
When trying to use the "History" text in the chat GUI to view a shops history, it does nothing, it only sends a ping sound.

No errors in console.

### Steps to reproduce

1. Use PurPur 1.18.2
2. Make a shop and get some sales!
3. As a shop owner try and view the shops history
4. Be sad it didn't work

### Expected Behaviour

To show shop history

### Screenshots

Posted in first box as im filling these boxes out in order.

### `/quickshop paste` URL

This is way too sensative to have public

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
![4e8f450d-66fb-4370-8796-24e7b987ad5e](https://github.com/user-attachments/assets/c77e07b6-b757-4347-9229-1e7414e11634)

**Comment by TomLewis** [comment]
Thanks for the quick reply.

**Comment by Etanarvazac** [comment]
Do wish instead of jumping to disable this, it was set as elevated perm... This helps solve headaches...

**Comment by creatorfromhell** [comment]
> Do wish instead of jumping to disable this, it was set as elevated perm... This helps solve headaches...

It was readded in the dev builds already.

**Comment by Etanarvazac** [comment]
> > Do wish instead of jumping to disable this, it was set as elevated perm... This helps solve headaches...
> 
> It was readded in the dev builds already.

Any updates to when this is live again?

**Comment by creatorfromhell** [comment]
> > > Do wish instead of jumping to disable this, it was set as elevated perm... This helps solve headaches...
> > 
> > It was readded in the dev builds already.
> 
> Any updates to when this is live again?

It's been live for months on the discord beta builds as stated in the post you responded to....

**Comment by Etanarvazac** [comment]
> > > > Do wish instead of jumping to disable this, it was set as elevated perm... This helps solve headaches...
> > > 
> > > 
> > > It was readded in the dev builds already.
> > 
> > 
> > Any updates to when this is live again?
> 
> It's been live for months on the discord beta builds as stated in the post you responded to....

I mean outside beta. But we may have a look into this given the rise in cases where it would've been helpful.

**Comment by creatorfromhell** [comment]
> > > > > Do wish instead of jumping to disable this, it was set as elevated perm... This helps solve headaches...
> > > > 
> > > > 
> > > > It was readded in the dev builds already.
> > > 
> > > 
> > > Any updates to when this is live again?
> > 
> > 
> > It's been live for months on the discord beta builds as stated in the post you responded to....
> 
> I mean outside beta. But we may have a look into this given the rise in cases where it would've been helpful.

Not outside the beta. If you wish to utilize it, use the beta builds.

**Comment by TomLewis** [comment]
Til a beta exists.
