### ISSUE TITLE
Combat-Towny Plugin Not Working Properly

### ISSUE THREAD

**Issue by pelicano0** [Ghost-chu/QuickShop-Hikari#1758]
### Description

I am using the latest versions of QuickShop-Hikari and Combat-Towny together, but I am unable to create shops both inside and outside of towns. I have configured the plugins, but nothing seems to change. Could this be a compatibility issue, or is there a specific setting I might be missing?

### Steps to reproduce

With the Towny, QuickShop-Hikari, and Combat-Towny plugins installed on your server, you will not be able to create markets either inside or outside of the town.

### Expected Behaviour

Allows the creation of markets inside the town but prevents it outside.

### `/quickshop paste` URL

https://paste.helpch.at/ejarisulax.yaml

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
> ### Description
> I am using the latest versions of QuickShop-Hikari and Combat-Towny together, but I am unable to create shops both inside and outside of towns. I have configured the plugins, but nothing seems to change. Could this be a compatibility issue, or is there a specific setting I might be missing?
> 
> ### Steps to reproduce
> With the Towny, QuickShop-Hikari, and Combat-Towny plugins installed on your server, you will not be able to create markets either inside or outside of the town.
> 
> ### Expected Behaviour
> Allows the creation of markets inside the town but prevents it outside.
> 
> ### Screenshots
> _No response_
> 
> ### `/quickshop paste` URL
> https://paste.helpch.at/ejarisulax.yaml
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [ ]  I'm running Paper or Spigot, and not a fork
> * [x]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

The compact plugin doesn't change the needs for permissions in the Towny plugin...

https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/compat-modules/towny#createpurchase-control

Per config/documentation provided to the end-user, the player still has to have build perms and/or ownership and/or be in a shop plot type in towny to create/trade with shops.
