### ISSUE TITLE
[BUG] Warning appears in the console

### ISSUE THREAD

**Issue by TBedu** [Ghost-chu/QuickShop-Hikari#1762]
### Description

At times, the console may output `Failed to load shop` `Unloading shops from memory, set 'debug.delete-corrupt-shops' to true to delete corrupted shops.`

### Steps to reproduce

1.Start the server normally
2.Players enter a certain area
3.Warning appears in the console

### Expected Behaviour

No warning will appear

### Screenshots

![image](https://github.com/user-attachments/assets/5f376cea-a8a6-4b2a-8600-bfd386a352a3)

### `/quickshop paste` URL

https://paste.helpch.at/oqotofuwoz.makefile

### Additional Context

It seems not

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
您有重置过世界吗，比如删除世界文件让它重新生成一个

**Comment by TBedu** [comment]
> 您有重置过世界吗，比如删除世界文件让它重新生成一个

Sorry, I haven't done that yet. However, resetting the world seems to lose all block data, so I cannot do so.   
If I really did this, how would I explain it to the players  

道歉，我还没有这样做。不过重置世界似乎会丢失所有区块数据，因此，我不能这样做。  
（如果我真的这样做了，那我如何向玩家们解释？）

**Comment by YuanYuanOwO** [comment]
> > 您有重置过世界吗，比如删除世界文件让它重新生成一个
> 
> Sorry, I haven't done that yet. However, resetting the world seems to lose all block data, so I cannot do so. If I really did this, how would I explain it to the players
> 
> 道歉，我还没有这样做。不过重置世界似乎会丢失所有区块数据，因此，我不能这样做。 （如果我真的这样做了，那我如何向玩家们解释？）

我的意思不是让你去重置世界，该警告一般会出现在被重置/刷新过的世界中，然后商店数据与世界数据对不上号就会这样。  
以及机翻可以用 DeepL

**Comment by TBedu** [comment]
> > > 您有重置过世界吗，比如删除世界文件让它重新生成一个
> > 
> > 
> > 抱歉，我还没有这样做。但是，重置世界似乎会丢失所有块数据，所以我不能这样做。如果我真的这样做了，我该如何向玩家解释
> > 道歉，我还没有这样做。不过重置世界似乎会丢失所有区块数据，因此，我不能这样做。（如果我真的这样做了，那我如何向玩家们解释？）
> 
> 我的意思不是让你去重置世界，该警告一般会出现在被重置/刷新过的世界中，然后商店数据与世界数据对不上号就会这样。 以及机翻可以用 DeepL

Never reset the world.  

从来没有重置世界。

**Comment by YuanYuanOwO** [comment]
Problems caused by using CoreProtect's rollback feature.
Problem solved after using /qs cleanghost.
