### ISSUE TITLE
[BUG] Display Items do not despawn anymore!

### ISSUE THREAD

**Issue by christinloehner** [Ghost-chu/QuickShop-Hikari#1771]
### Description

Is there any chance to get rid of these display item artefacts?? 
When I created my first five or six chestshops, I had display-type set to 2. But I have no ProtocolLib. So I changed that to 0. Then restarted the server. After that I did /shop remove on these chests and broke the chests. But these display items are still there and don't go away. they also already survived three server restarts...

### Steps to reproduce

1. install the plugin into a server without protocolLib
2. check, that display type is set to 2
3. restart the server
4. create some chestshops
5. change display type to 0
6. restart the server
7. remove the previously created shops

### Expected Behaviour

quickshop should remove all display-items when removing a shop sign.

### Screenshots

![2024-09-19_14 26 03](https://github.com/user-attachments/assets/eb25b50c-3ad6-4312-b526-97dce83dab6c)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FUXYnBuzDjH

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
> ### Description
> Is there any chance to get rid of these display item artefacts?? When I created my first five or six chestshops, I had display-type set to 2. But I have no ProtocolLib. So I changed that to 0. Then restarted the server. After that I did /shop remove on these chests and broke the chests. But these display items are still there and don't go away. they also already survived three server restarts...
> 
> ### Steps to reproduce
> 1. install the plugin into a server without protocolLib
> 2. check, that display type is set to 2
> 3. restart the server
> 4. create some chestshops
> 5. change display type to 0
> 6. restart the server
> 7. remove the previously created shops
> 
> ### Expected Behaviour
> quickshop should remove all display-items when removing a shop sign.
> 
> ### Screenshots
> ![2024-09-19_14 26 03](https://private-user-images.githubusercontent.com/1255288/369031035-eb25b50c-3ad6-4312-b526-97dce83dab6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTc1NjgsIm5iZiI6MTcyNjc1NzI2OCwicGF0aCI6Ii8xMjU1Mjg4LzM2OTAzMTAzNS1lYjI1YjUwYy0zYWQ2LTQzMTItYjUyNi05N2RjZTgzZGFiNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTQ0NzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWViM2FlMWM1ZWRjMTJjZTlmOGRiMzcwMWUzMGJjOWFiZTM4NDdiOGYxMmRmNzE0ZDhjODFkNjYyNWU5Y2RjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YJ_qHSN_YzeZdE-bhAfYamw52yWGRKD2oq-CHGeN93U)
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FUXYnBuzDjH
> 
> ### Additional Context
> _No response_
> 
> ### Checklist
> * [x]  I'm running Paper or Spigot, and not a fork
> * [x]  I confirm that Paper/Spigot has been updated to the latest build
> * [x]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [x]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [x]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [x]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

Display type 0 is being removed because it provides no significant improvements, add protocol lib and use type 2 or disable displays. In order to o remove the bugged items after doing the change, use the appropriate CMI, essentials or vanilla command for killing display entities, which is also listed in the discord.
