### ISSUE TITLE
[BUG] Duplicated Bug (Needs fixing asap)

### ISSUE THREAD

**Issue by DrSnowPengu** [Ghost-chu/QuickShop-Hikari#1779]
### Description

When a shop is created, on the view items display, it stacked on top and kept there, but when you mine it and put the hopper under it, it drops inside and picked it up. It looks like it stacks like more than 1 items.

### Steps to reproduce

1. Make A shop by using the items while you are holding it
2. change the settings in the shop (toggle item) to and revert it back
3. when done,  the items displayed should be stacked it double
4. if done, remove the shop while there are hoppers under it
5. when done it correctly, the items for display will drop and the hopper can get the items
and it will be duplicated.

note*
when holding more than 1 items when creating the shop,  the items duplicated will be corresponding with the amount of the items held when creating

### Expected Behaviour

So that the items doesn't duplicate.

### Screenshots

Here is an example of the bug where players can duplicate the items - https://gyazo.com/2dfd7f79b862d7c7736a8b9b212a1ea2

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2Fxup58qO3tZ

### Additional Context

I am running Pufferfish 1.21.1 and QuickShop-Hikari 6.2.0.7

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [ ] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [ ] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [ ] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [ ] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
> ### Description
> When a shop is created, on the view items display, it stacked on top and kept there, but when you mine it and put the hopper under it, it drops inside and picked it up. It looks like it stacks like more than 1 items.
> 
> ### Steps to reproduce
> 1. Make A shop by using the items while you are holding it
> 2. change the settings in the shop (toggle item) to and revert it back
> 3. when done,  the items displayed should be stacked it double
> 4. if done, remove the shop while there are hoppers under it
> 5. when done it correctly, the items for display will drop and the hopper can get the items
>    and it will be duplicated.
> 
> note* when holding more than 1 items when creating the shop, the items duplicated will be corresponding with the amount of the items held when creating
> 
> ### Expected Behaviour
> So that the items doesn't duplicate.
> 
> ### Screenshots
> Here is an example of the bug where players can duplicate the items - https://gyazo.com/2dfd7f79b862d7c7736a8b9b212a1ea2
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2Fxup58qO3tZ
> 
> ### Additional Context
> I am running Pufferfish 1.21.1 and QuickShop-Hikari 6.2.0.7
> 
> ### Checklist
> * [ ]  I'm running Paper or Spigot, and not a fork
> * [ ]  I confirm that Paper/Spigot has been updated to the latest build
> * [ ]  I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
> * [ ]  I confirm that I have not read these checkboxes and therefore I just ticked them all.
> * [ ]  I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
> * [ ]  I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
> * [ ]  I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

Real Item Display isn't supported anymore, in fact, it has been removed in the latest dev builds. Use virtual item display with protocollib.
