### ISSUE TITLE
 Unsupported plugin management plugin [GroupManager]

### ISSUE THREAD

**Issue by Seasonull** [Ghost-chu/QuickShop-Hikari#1782]
### Description

Curious if it would be possible to get  [GroupManager](https://www.spigotmc.org/resources/groupmanager.38875/) (og perm manager plugin that's been around for a while) support and if not, is it okay to continue using GMan? I don't seem to have any issues so far that I've noticed or any that players have brought to attention.

I see this every startup: `[WARN]: [QuickShop-Hikari] [WARN] Permission Manager Test: WARNING: Unsupported plugin management plugin [GroupManager] installed, the permissions may not working.`

Hoping this is the right spot. Spigot page just says open an issue on github for plugin compatibility.

### Steps to reproduce

Start server with QuickShop while using GroupManager.

### Expected Behaviour

Support GroupManager.

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FccRpGleUBb

### Spark Sample URL

https://spark.lucko.me/OWMMJLn5iu

**Comment by YuanYuanOwO** [comment]
i think it's safe to ignore if you are without any issue
