### ISSUE TITLE
[BUG] [Towny Compat] Incorrect Create Checks

### ISSUE THREAD

**Issue by DarioMavilia** [Ghost-chu/QuickShop-Hikari#1785]
### Description

When using the `create: -MODIFY` checks for creating a new chest shop, it checks for modify permissions **and** if it's a shop plot. This is incorrect according to the documentation.

### Steps to reproduce

1. Run QS with the towny compatibility module.
2. Have only the modify check on the create shop section of the config.
3. Try to create a shop in a non-shop plot but in an area you have permission to build.
4. Shop is unable to be made.

### Expected Behaviour

Shop should be created.

### `/quickshop paste` URL

consolespamfix-installed

### Additional Context

`quickshop-paste` doesn't generate a link. It only prints `consolespamfix-installed`.

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
please try this command
/qs paste --force

**Comment by DarioMavilia** [comment]
https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FPMiatb6M95

@YuanYuanOwO

**Comment by creatorfromhell** [comment]
This seems more like an issue with the documentation than the functionality. The whole reason the shop plot type is there is for this purpose. OWN also checks for Shop Plot.

**Comment by DarioMavilia** [comment]
Can I ask that it not be the case? 

Shop plot should check for shop plots, modify should ONLY check for modify in my opinion. Maybe this should be a toggleable feature if you don't want it on by default.

**Comment by creatorfromhell** [comment]
Adjusted in PR #1781 .
