### ISSUE TITLE
[BUG] qs history cannot be use in folia

### ISSUE THREAD

**Issue by cgw2023** [Ghost-chu/QuickShop-Hikari#1787]
### Description

using version c9d4d6c6b0ebfcad808ecc8ab4cd5bebbcd4a5e8
when `/qs history` is used, error occurs, menu cannot be displayed.

### Steps to reproduce

1. use `/qs history`

`/qs history` can be used if the server is launched in paper/purpur, but not folia with the same qs files

### Expected Behaviour

menu can be shown

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FdVgggWjzeX

### Checklist

- [ ] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
Post the full error please

**Comment by cgw2023** [comment]
> Post the full error please
here it is
https://mclo.gs/zq4tr2N

**Comment by creatorfromhell** [comment]
> > Post the full error please
> > here it is
> > https://mclo.gs/zq4tr2N

[QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/17528311/QuickShop-Hikari-6.2.0.7.zip)

**Comment by cgw2023** [comment]
> > > Post the full error please
> > > here it is
> > > https://mclo.gs/zq4tr2N
> 
> [QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/17528311/QuickShop-Hikari-6.2.0.7.zip)

great, it is working, thank you so much

**Comment by cgw2023** [comment]
> > > Post the full error please
> > > here it is
> > > https://mclo.gs/zq4tr2N
> 
> [QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/17528311/QuickShop-Hikari-6.2.0.7.zip)

good news, it works. but bad news, it broke addon API seems like
`[00:37:07 ERROR]: [qsaddon-discordsrv] Failed to register events for class com.ghostchu.quickshop.addon.discordsrv.listener.QuickShopEventListener because com/ghostchu/quickshop/api/event/ShopOwnershipTransferEvent does not exist.
`
`[00:37:01 ERROR]: [QuickShopForm] Failed to register events for class ltd.rymc.form.quickshop.handler.ShopHandlerHikari because com/ghostchu/quickshop/api/event/ShopClickEvent does not exist.
`

**Comment by creatorfromhell** [comment]
> > > > Post the full error please
> > > > here it is
> > > > https://mclo.gs/zq4tr2N
> > 
> > [QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/17528311/QuickShop-Hikari-6.2.0.7.zip)
> 
> good news, it works. but bad news, it broke addon API seems like
> `[00:37:07 ERROR]: [qsaddon-discordsrv] Failed to register events for class com.ghostchu.quickshop.addon.discordsrv.listener.QuickShopEventListener because com/ghostchu/quickshop/api/event/ShopOwnershipTransferEvent does not exist.
> `
> `[00:37:01 ERROR]: [QuickShopForm] Failed to register events for class ltd.rymc.form.quickshop.handler.ShopHandlerHikari because com/ghostchu/quickshop/api/event/ShopClickEvent does not exist.
> `

Nah this was broke on other commits, the local add-on builds are already are fixed

**Comment by cgw2023** [comment]
> > > > > Post the full error please
> > > > > here it is
> > > > > https://mclo.gs/zq4tr2N
> > > 
> > > 
> > > [QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/17528311/QuickShop-Hikari-6.2.0.7.zip)
> > 
> > 
> > good news, it works. but bad news, it broke addon API seems like
> > `[00:37:07 ERROR]: [qsaddon-discordsrv] Failed to register events for class com.ghostchu.quickshop.addon.discordsrv.listener.QuickShopEventListener because com/ghostchu/quickshop/api/event/ShopOwnershipTransferEvent does not exist. `
> > `[00:37:01 ERROR]: [QuickShopForm] Failed to register events for class ltd.rymc.form.quickshop.handler.ShopHandlerHikari because com/ghostchu/quickshop/api/event/ShopClickEvent does not exist. `
> 
> Nah this was broke on other commits, the local add-on builds are already are fixed

I don't have such problem when I build the jar with c9d4d6c6b0ebfcad808ecc8ab4cd5bebbcd4a5e8 , may I ask, how do I get a jar that can have these addon listener and `qs history` work together? which/any version or branch i can build by myself?

**Comment by creatorfromhell** [comment]
> > > > > > Post the full error please
> > > > > > here it is
> > > > > > https://mclo.gs/zq4tr2N
> > > > 
> > > > 
> > > > [QuickShop-Hikari-6.2.0.7.zip](https://github.com/user-attachments/files/17528311/QuickShop-Hikari-6.2.0.7.zip)
> > > 
> > > 
> > > good news, it works. but bad news, it broke addon API seems like
> > > `[00:37:07 ERROR]: [qsaddon-discordsrv] Failed to register events for class com.ghostchu.quickshop.addon.discordsrv.listener.QuickShopEventListener because com/ghostchu/quickshop/api/event/ShopOwnershipTransferEvent does not exist. `
> > > `[00:37:01 ERROR]: [QuickShopForm] Failed to register events for class ltd.rymc.form.quickshop.handler.ShopHandlerHikari because com/ghostchu/quickshop/api/event/ShopClickEvent does not exist. `
> > 
> > 
> > Nah this was broke on other commits, the local add-on builds are already are fixed
> 
> I don't have such problem when I build the jar with [c9d4d6c](https://github.com/QuickShop-Community/QuickShop-Hikari/commit/c9d4d6c6b0ebfcad808ecc8ab4cd5bebbcd4a5e8) , may I ask, how do I get a jar that can have these addon listener and `qs history` work together? which/any version or branch i can build by myself?

it's in my PR #1781 . I'll be posting the updated addon jars in the discord momentarily.

**Comment by creatorfromhell** [comment]
Builds have been released on discord.
