### ISSUE TITLE
复制bug

### ISSUE THREAD

**Issue by 404forever1** [Ghost-chu/QuickShop-Hikari#1813]
![image](https://github.com/user-attachments/assets/7bed8112-8697-46ab-89fb-f6a1c5e247d0)
![image](https://github.com/user-attachments/assets/13a84112-bce8-450c-a996-129961198449)
将虚浮物品挤下去，就可以被矿车接收

**Comment by YuanYuanOwO** [comment]
下次用英文，按照模板开启issue，不按模板来直接关了
你没有使用虚拟悬浮物，请安装 ProtocolLib 并调整 display-type 为 2
