### ISSUE TITLE
[BUG] SSLHandshakeException

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Hikari#183]
### Description

At one random point was QuickShop printing SSLHandshakeExceptions like this one:
https://paste.helpch.at/azojozasad.bash

This seems to be caused by the CI (CodeMC) not having a valid SSL certificate for some reason.
While this issue should be fixed by now would I say that QS should try to properly catch this exception and return a nicer warning, in case this ever happens again.

### Steps to reproduce

1. You can't really reproduce this anymore as it *should* be fixed. Tho it's not guaranteed.

### Expected Behaviour

Not printing a ton of stacktraces

### Screenshots

N/A

### `/qs paste` URL

https://paste.helpch.at/vemoyovolu

**Comment by Ghost-chu** [comment]
Unfortunately I am currently in the hospital receiving treatment and I will fix this problem as soon as my body recovers.
