### ISSUE TITLE
[BUG] Players cannot purchase shop items in Adventure mode

### ISSUE THREAD

**Issue by Junnstoy** [Ghost-chu/QuickShop-Hikari#229]
### Description

Players cannot purchase shop items in Adventure mode.
In  Remake version, the feature works fine.

### Steps to reproduce

Switch to Adventure Mode,Left-click on the wooden sign,Nothing happens.

### Expected Behaviour

I want players to be able to use it in adventure mode.As long as the player can use the buy and sell functions normally.Is there any way to solve it?

### Screenshots

NA

### `/qs paste` URL

NA

**Comment by Ghost-chu** [comment]
Please provide paste URL.
