### ISSUE TITLE
An unexpected error cannot be created by anyone

### ISSUE THREAD

**Issue by 9xbo** [Ghost-chu/QuickShop-Hikari#240]
http://image.rustbot.cn:11316/yx/55555.png
An unexpected error cannot be created by anyone

**Comment by Ghost-chu** [comment]
Spartan anti-cheat blocking it.
Add new entry `- @Spartan` in listener black list.
https://github.com/Ghost-chu/QuickShop-Hikari/blob/9d17333c61115ac93c465bafdddc9e7c7d5468ee/quickshop-bukkit/src/main/resources/config.yml#L393

**Comment by 9xbo** [comment]
How to set

  protection-checking-listener-blacklist:
  - ignored_listener
  - ignored_Spartan

  protection-checking-listener-blacklist:
  - ignored_listener
  - @Spartan

  protection-checking-listener-blacklist:
  - ignored_listener
  - Spartan

**Comment by Ghost-chu** [comment]
> How to set
> 
> protection-checking-listener-blacklist:
> 
> * ignored_listener
> * ignored_Spartan
> 
> protection-checking-listener-blacklist:
> 
> * ignored_listener
> * @spartan
> 
> protection-checking-listener-blacklist:
> 
> * ignored_listener
> * Spartan

```
protection-checking-listener-blacklist:
  - @Spartan
```

**Comment by 9xbo** [comment]
I'm sorry I'm a little stupid

After change

/quickshop reload

Still http://image.rustbot.cn:11316/yx/55555.png

**Comment by 9xbo** [comment]
protection-checking-listener-blacklist:
  - @Spartan

**Comment by 9xbo** [comment]
>   protection-checking-listener-blacklist:
  - @Spartan

**Comment by Ghost-chu** [comment]
`/qs paste` to generate debug report.

**Comment by 9xbo** [comment]
`  protection-checking-listener-blacklist:
  - @Spartan`

**Comment by 9xbo** [comment]
> /qs 粘贴以生成调试报告。

ok

**Comment by 9xbo** [comment]
http://image.rustbot.cn:11316/yx/paste-be75c758cf854f8a833740b5584d843c.html

**Comment by 9xbo** [comment]
Did you see it? If you saw it, I deleted it

**Comment by Ghost-chu** [comment]
Try
```yaml
protection-checking-listener-blacklist:
  - "@Spartan"
```

**Comment by 9xbo** [comment]
ke yi le  !  thank you !

**Comment by Ghost-chu** [comment]
Have a good day.
