### ISSUE TITLE
[Feature] qs_data table clean up helper

### ISSUE THREAD

**Issue by Ghost-chu** [Ghost-chu/QuickShop-Hikari#281]
Because the new database schema and [this bug](https://github.com/Ghost-chu/QuickShop-Hikari/commit/6e63cb26f6b2e2023377216154cf36f24d9b7649), `qs_data` and `qs_shops` may have lots of unused data exists.

We need a tool that allow us to clean up the tables above.

Goal:

- Check and delete shop ids if they are not in used by other tables.
- Check and delete data ids if they are not in used by other tables.
- Bump database version to `5` and execute cleanup above when bumping version.

**Comment by CarmJos** [comment]
Caption, my caption! job is done. See https://github.com/Ghost-chu/QuickShop-Hikari/commit/47b92c21b84928127505231b900fb27c874b6e5b .
