### ISSUE TITLE
[TODO] Add a way to divide benefits between owner and staff member of a shop

### ISSUE THREAD

**Issue by Ghost-chu** [Ghost-chu/QuickShop-Hikari#30]
https://github.com/Ghost-chu/QuickShop-Reremake/issues/578

**Comment by kohle** [comment]
+1 for this idea! Maybe a percentage could be set for each player when adding them as staff, along the lines of `/qs staff add <player> [sales %]`

**Comment by Ghost-chu** [comment]
@kohle @Chris6ix @Bloodlex
This feature now implemented into master development branch.

Usage:

```
/qs benefit <add/remove/query> <player> <percentage>
```

Example: 

Shop owner `Ghost_chu` created a shop that selling Apple for 100$ each.
Use command `/qs benefit add Foobar 50%` to add `Foobar` player into benefits.
Then player bought a Apple from this shop, `Foobar` will get `100*0.5=50$` and all remains money `100-50=50$` will give to shop owner `Ghost_chu`.

If there have 20$ taxes, it will become:
`Foobar` will get `80*0.5=40$` and shop owner will get `80-40=40$` only. 

This feature only applied to SELLING shops, won't affect the BUYING shops.

**Comment by Ghost-chu** [comment]
This feature finally added into QuickShop after two years later 🤣

**Comment by Ghost-chu** [comment]
snapshot available here: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Hikari-SNAPSHOT/1001/
