### ISSUE TITLE
[Feature] Treasury Support

### ISSUE THREAD

**Issue by Ghost-chu** [Ghost-chu/QuickShop-Hikari#449]
https://github.com/Ghost-chu/QuickShop-Hikari/discussions/448

**Comment by creatorfromhell** [comment]
Adding my two cents - I don't know how widely used it currently is.

**Comment by Ghost-chu** [comment]
> Adding my two cents - I don't know how widely used it currently is.

Not really wide: https://bstats.org/plugin/bukkit/Treasury/12927

There is no good reason to replace Vault, which still works very well, meets the needs of the vast majority of users, and is easy to use.

**Comment by creatorfromhell** [comment]
Treasury development has stalled.
