### ISSUE TITLE
[BUG] InventoryWrapper should return a map.

### ISSUE THREAD

**Issue by CarmJos** [Ghost-chu/QuickShop-Hikari#487]
### Description

 InventoryWrapper should return a map which contains the items haven't been removed.

### Steps to reproduce

1. use `InventoryWrapper#removeItems` method.

### Expected Behaviour

https://github.com/Ghost-chu/QuickShop-Hikari/blob/26ae78e20537b45b1a256965f898cf822a72e8ae/quickshop-api/src/main/java/com/ghostchu/quickshop/api/inventory/InventoryWrapper.java#L147

A method like "InventoryWrapper#removeItemsWithRemains" is required, which has same behavior with `InventoryWrapper#removeItems` method but will return a Map containing the items haven't been removed.

### Screenshots

Nothing

### `/qs paste` URL

https://github.com/Ghost-chu/QuickShop-Hikari/blob/26ae78e20537b45b1a256965f898cf822a72e8ae/quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/operation/RemoveItemOperation.java#L46

**Comment by Ghost-chu** [comment]
sounds great

**Comment by Ghost-chu** [comment]
closed since system has been refactoed.
