### ISSUE TITLE
[BUG] Plugin causes "Invalid move player packet received" kicks upon teleports with Papers anti-xray enabled

### ISSUE THREAD

**Issue by x86-39** [Ghost-chu/QuickShop-Hikari#516]
### Description

Upon teleporting some distance, players are occasionally kicked with an invalid move player packet error. This error was narrowed down to being caused by QuickShop after sequentially removing plugins from the server one by one until the kick no longer happened, and then adding QuickShop back to verify that the kick once again occurred after reinstalling it. Appears to only happen when one of the teleportation locations involved has shops nearby.

Minimum number of plugins installed that I tried while still getting the kick:
LWCX 2.2.7
EssentialsX
EssentialsX AntiBuild
EssentialsX Chat
EssentialsX Protect
EssentialsX Spawn
ProtocolLib
QuickShop Hikari 3.3.0.1

Console output during kick (/b is our server's alias for the Essentials /back command):
```
13:58:47
maeeeeee issued server command: /b
maeeeeee issued server command: /b
13:58:48
maeeeeee issued server command: /b
maeeeeee issued server command: /b
maeeeeee lost connection: Invalid move player packet received
-maeeeeee has left for now.
```

Spamming /back from EssentialsX between two areas far apart where at least one of the areas has a QuickShop shop loaded.
I'm using a mod [Command Macros](https://www.curseforge.com/minecraft/mc-mods/command-macros) to send /back every 100ms.
Of course spamming it so much isn't representative, but this is a way to replicate the issue. This just often happens out of nowhere to players when teleporting. It seems to happen to some players more than others so connection speed could be a part of it, but I'm seeing it happen to about every player. Checking through logs we've had this happen 985 times since October 15th.

### Steps to reproduce

1. Teleport to a location. Several different plugins were used for teleporting, such as EssentialsX, MyWarp, and others, and each caused the issue.
2. Player is occasionally kicked from the server.

To consistently reproduce using EssentialsX, teleport somewhere (/tpr works for this) and then spam /back until the issue occurs.

### Expected Behaviour

Plugin should not be causing players to be kicked upon teleports.

### Screenshots

[Minecraft.2022.11.12.-.13.57.55.03.mp4](https://user-images.githubusercontent.com/52181624/201490494-7fb29f92-)e23a-4707-81b7-b76f040abeee.mp4

### `/qs paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FV6Wy3DZ5yz

### Additional Context

Duplicate of https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/255

Can replicate with paper-1.19.2-265 with the following plugins:

* Vault
* QuickShop Hikari 3.3.0.1, downloaded from latest Modrinth
* Protocollib
* EssentialsX

All configs set to default, except for:
Changed config/paper-world-defaults.yml and setting anticheat.anti-xray.enabled to true.

Spamming /back from EssentialsX between two areas far apart where at least one of the areas has a QuickShop shop loaded.
I'm using a mod [Command Macros](https://www.curseforge.com/minecraft/mc-mods/command-macros) to send /back every 100ms.
Of course spamming it so much isn't representative, but this is a way to replicate the issue. This just often happens out of nowhere to players when teleporting. It seems to happen to some players more than others so connection speed could be a part of it, but I'm seeing it happen to about every player. Checking through logs we've had this happen 985 times since October 15th. This is when we updated to Paper 1.19 and Quickshop 5.1.0.9.

**Comment by Ghost-chu** [comment]
We're QuickShop-Hikari fork which internal logic TOTALLY different with Reremake.

Seems you're running QuickShop-Reremake, please report it to PotatoCraft Studio.

We only accept the report related Hikari, if this issue also appears on Hikari, please use Hikari's `/qs paste` to create a QuickShop V2 Paste link and open an new issue without any Reremake stuff.

**Comment by x86-39** [comment]
Will get a new `qs paste` in a bit, I was able to replicate this on QS Hikari too.

**Comment by Ghost-chu** [comment]
Did you have client mods like Optifine installed?

**Comment by x86-39** [comment]
A lot of client mods yes but this issue happens for people on vanilla clients too. @maeeeeee replicated this issue too on a vanilla client
