### ISSUE TITLE
[BUG] 胆气这么小 不如 源码也全删了吧 听风就是雨 

### ISSUE THREAD

**Issue by Hanmingxuan** [Ghost-chu/QuickShop-Hikari#783]
### Description

PS. 关于网易一事，可以看 这个动态 …… 作者：龙腾猫跃https://t.bilibili.com/763551069842178161 出处：bilibili

### Steps to reproduce

Q：听说因为网易，PCL 的更新发不出去了？ 
A：没有。只是之前有次更新动态被 B 站嘎了，但同样的内容换成专栏就能发。我怀疑是叔叔那边抽风（当时配了个樱桃炸弹 Cherry Bomb 的图，谐音梗 (图像: [妙啊])），现在用专栏发没有遇到什么问题。这事目前没任何证据和网易有关，还请不要牵强附会。 

Q：听说有启动器作者被网易告了，要关三年？ 
A：瞎编的……实际上是网传某商业服服主被网易告了（我也不确定此事真伪），结果不知道是谁传着传着把这事的主角嫁接到启动器作者头上了 (图像: [无语])…… 

Q：但另一个启动器已经被网易举报了啊？ 
A：TT 的一个宣传视频被网易下了，但也仅限于视频，而不是启动器被举报了。虽然这事的原因并不清楚，但如果网易真要像某些 UP 传的那样拳打国际版脚踢第三方，那直接找启动器就行了，单找一个视频干嘛？ 

Q：那你有被网易约谈要求删除 XX 功能吗？ 
A：没有，纯属瞎编。 

Q：网易有联系过启动器作者吗？ 
A：我认识的作者里，没有…… 

### Expected Behaviour

Q：但真的有好几个 UP 说你已经被告了诶？ 
A：没！！！妈耶，我现在每天睡醒感觉看一眼 B 站都能看到有的 UP 把我的坟都挖好了，评论区都准备沉痛悼念了，是不是再等几天那些 UP 都要给我送花圈放大悲咒了啊？(图像: [辣眼睛]) 

### Screenshots

Q：所以这件事到底是咋回事？ 
A：单说启动器这边，除了 TT 的一个视频被举报了以外，网传的所有消息都是现编的。特别是最近几天，这事已经成为了 B 站某些 UP 的流量密码，拱一拱火，编一编故事，煽一煽情，给启动器 Logo 搞个黑白立个坟头，大家骂起来了，火冒三丈了，流量就恰到了。就怕是网易自己都是懵逼的，人在公司坐，锅从天上来，故事编的好，流量少不了。网传的真话就没几句，希望各位不要被骗被带节奏才好…… 等事情过去，我会把这个动态删了。 多谢各位，别再看几句谣言就来沉痛悼念了，人还活着呢，再悼念都要念死了……

### `/qs paste` URL

https://t.bilibili.com/763551069842178161

### Additional Context

666

**Comment by Ghost-chu** [comment]
```
-Dcom.ghostchu.quickshop.util.envcheck.EnvironmentChecker.skip.LEGAL_COMPLIANCE_CHECK=true
```
你有选择其他插件的权利。

**Comment by Ghost-chu** [comment]
对其它查看 Issue 的用户：

相关问题的具体情况我很早就知道了，此楼附图：  
![image](https://user-images.githubusercontent.com/30802565/221368516-f9f8164c-239d-40e5-82d2-d59cdb7979c8.png)

**Comment by Hanmingxuan** [comment]
哈哈哈 这个作者真好🤣 不如Email给我 你那个参数怎么用 谢谢
qyff.me@qq.com

**Comment by Ghost-chu** [comment]
```
java -Xmx4G ... <参数放这里&gt; ... -jar server.jar nogui
```



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月26日(周日) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Ghost-chu/QuickShop-Hikari] [BUG] 胆气这么小 不如 源码也全删了吧 听风就是雨  (Issue #783)




 
哈哈哈 这个作者真好🤣 不如Email给我 你那个参数怎么用 谢谢
 ***@***.***

**Comment by Hanmingxuan** [comment]
额 也不是不行 我还是觉得 直接删相关代码 再编译 更好

**Comment by YuanYuanOwO** [comment]
https://github.com/carm-outsource/QuickShop-Hikari-Cracker

**Comment by Hanmingxuan** [comment]
> https://github.com/carm-outsource/QuickShop-Hikari-Cracker

6但是我不喜欢这个名字🤣
free(dom )或者 open 更合适一点

**Comment by Hanmingxuan** [comment]
怎么又蹦出来一个人😁

**Comment by Ghost-chu** [comment]
这套机制设计的目的本身就是仅仅为了短期内规避法律风险。

* 你能够通过启动参数轻松禁用检测
* 禁用检测的过程是可以完全自动化的
* 基于 CloudFlare API 的地理位置检测实际上非常不可靠，用户禁止访问 CF API 或者服务器无法访问 CF API，检测失败后，限制也不会启用
* 没有上更加严格的检测，并且这些检测理论上会更加可靠（检测操作系统语言、检测 ESSX 等其他插件的配置文件的语言设定等等）
* 在插件限制被添加之前，我已经在部分群里公告了限制去除方法
* 你可以使用上一个不受限制的历史版本
* 源代码是开放的，你完全可以自行修改

我完全没有打算趁火打劫，亦或是蹭热度吸血等想法。  
如果这也算是听风就是雨，那上面这些你就看作大雨底下路旁的一棵树吧。可以躲，也可以淋雨，选择权在用户手中。

**Comment by Hanmingxuan** [comment]
是我 信息闭塞[抱拳]
