### ISSUE TITLE
[BUG] Issue with Addon-DiscordSRV and Papers New Plugin Loader

### ISSUE THREAD

**Issue by Spaex** [Ghost-chu/QuickShop-Hikari#786]
### Description

Seems like Addon-DiscordSRV has some issues with Paper's new Plugin Loader System. Included the error message in the pastebin.

https://pastebin.com/u3Tq3Xue

### Steps to reproduce

1. Create a PaperMC Server with Paper 1.19.3 405 or later 
2. Add Quickshop Hikari and Addon-DiscordSRV + DiscordSRV
3. The Addon won't start.

### Expected Behaviour

The plugin should enable

### Screenshots

![grafik](https://user-images.githubusercontent.com/46825907/221547243-cf5375c6-20a8-43b7-b145-ee2f2c03d226.png)

### `/qs paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2Fpy02tGelpB

**Comment by Ghost-chu** [comment]
This appears to be a Paper bug.  
Addon needs to use the dependency libraries from the QuickShop-Hikari, which is provided by the Bukkit dependency loader.

Addon depends on QuickShop-Hikari at here: 
https://github.com/Ghost-chu/QuickShop-Hikari/blob/92b2bbbfe4e8acbc10b79b6ffa4abf8d8260ccac/addon/discordsrv/src/main/resources/plugin.yml#L5-L6

And Bukkit should inject the dependencies into runtime which we defined dependencies in plugin.yml in here:
https://github.com/Ghost-chu/QuickShop-Hikari/blob/92b2bbbfe4e8acbc10b79b6ffa4abf8d8260ccac/quickshop-bukkit/src/main/resources/plugin.yml#L16-L24

Paper appears to break the plugin's dependency passing, at least the behavior is different from Spigot.

Maybe you want to open an issue on the Paper side.

**Comment by Ghost-chu** [comment]
Is this problem still present in the latest Paper?

**Comment by Ghost-chu** [comment]
Paper seems fixed up it in https://github.com/PaperMC/Paper/pull/8938, closed.

If this issue re-appears, feel free to re-open it.
