### ISSUE TITLE
[BUG] When set max price restriction, cannot create shop

### ISSUE THREAD

**Issue by KioProject123** [Ghost-chu/QuickShop-Hikari#93]
### Description

view screenshots

### Steps to reproduce

undefined: # This option not control by enable option, always enabled
  min: 0.01 # Can be zero if you want player create a free shop
  max: 100000000 # Actually this can be up to 1.7976931348623157E308

### Expected Behaviour

.

### Screenshots

![@19U~ ~ M`NWN$6YSCUV~JQ](https://user-images.githubusercontent.com/61594596/159658768-6d3c81f5-8c94-41ae-b5b3-aa2c3d51fa87.png)

### `/qs paste` URL

.

**Comment by Ghost-chu** [comment]
please zip your configurations including config.yml and price-restriction.yml

**Comment by KioProject123** [comment]
[Z.zip](https://github.com/Ghost-chu/QuickShop-Hikari/files/8332006/Z.zip)
