### ISSUE TITLE
[BUG] ShopPurchaseEvent set total price Incorrect display

### ISSUE THREAD

**Issue by KioProject123** [Ghost-chu/QuickShop-Hikari#94]
### Description

This problem has been fed back before. fixed on Quickshop-remake, but not on QuickShop-Hikari

### Steps to reproduce

.

### Expected Behaviour

.

### Screenshots

![QQ截图20220323164647](https://user-images.githubusercontent.com/61594596/159659900-a0baeff1-dfd5-4b09-b9ec-120d37818a4b.png)
![unknown](https://user-images.githubusercontent.com/61594596/159659998-8860a475-9547-4432-bc30-d241d52bac03.png)

### `/qs paste` URL

.

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Hikari/blob/18fd9c6f07832a09ccb30baaf692e730d9999d39/quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/SimpleShopManager.java#L1126

https://github.com/Ghost-chu/QuickShop-Hikari/blob/18fd9c6f07832a09ccb30baaf692e730d9999d39/quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/SimpleShopManager.java#L726
