### ISSUE TITLE
[BUG] Incompatibility with WildTools

### ISSUE THREAD

**Issue by Distolfix** [Ghost-chu/QuickShop-Hikari#963]
### Description

When WildTools is installed, if a user is on the same island (SuperiorSkyblock2), it's possible with the sellwand to sell items of other players even though they cannot open their chests (this only happens if they are on the same island).

### Steps to reproduce

1) Create a shop on your island
2) A friend from your island needs to get a SellWand
3) If your friend clicks on your chest with the sellwand, it sells it even though he does not have access

### Expected Behaviour

The system should block the sale of the chest since it is protected.

### Screenshots

https://youtu.be/grH9nBtPRbk

### `/qs paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FyIXoV1HEZT

### Additional Context

I opened another Github to omar :

https://github.com/BG-Software-LLC/WildTools/issues/155 

Omar asked me to create a custom plugin, but I'm asking you instead to integrate this resolution.

**Comment by Distolfix** [comment]
In the video, since I was alone, I tried to reproduce it independently, but the principle is the same. If I create a crate, a player can sell it even though they shouldn't.

**Comment by Ghost-chu** [comment]
Does your friend have permission on that land to build or interact?

**Comment by Distolfix** [comment]
Yes

**Comment by Distolfix** [comment]
They have permission to build, but they should not be allowed to sell chests using the sell wand. In fact, on the same island, they cannot open other people's stores, but they can sell with the sell wand.

**Comment by Ghost-chu** [comment]
> They have permission to build, but they should not be allowed to sell chests using the sell wand. In fact, on the same island, they cannot open other people's stores, but they can sell with the sell wand.

Please upload your WildTools configuration

**Comment by Distolfix** [comment]
https://pastebin.com/TePjQ3tZ

**Comment by Ghost-chu** [comment]
> https://pastebin.com/TePjQ3tZ

Seems the WildTools configuration is correctly.

I just watched your video and seems it is a intended behavior for me.

Please note: QuickShop-Hikari won't add the protection to Server Administrators,  Shop Owner, Shop Staffs, and Island owner (if you have compatibility module installed).

From your video, you exempt yourself in the Skyblock plugin so you can access the any container in that island, and then you created a shop by your self so you also exempt yourself in the QuickShop-Hikari, you can sell the items in that container of course.

If you need to test for permission issues, you should always test with another clean alt account that no OP or other bypass permissions.

**Comment by Distolfix** [comment]
I'll make a video so you can understand better. Wait 5 minutes.

**Comment by Distolfix** [comment]
I apologize for the wasted time, but in the latest Quickshop update, the issue affecting the previous version seems to have been resolved. Testing it now, it works correctly. I apologize again.
