### ISSUE TITLE
[BUG] it can't connect mysql server for a lower mysql version..

### ISSUE THREAD

**Issue by 164ebr** [Ghost-chu/QuickShop-Hikari#975]
### Description

the main report..

https://paste.helpch.at/ikofuhajel.less

I wonder if he doesn't support lower versions of MySQL. I am using MySQL 5.5..

If possible, please fix it. This plugin is very important to me..

### Steps to reproduce

N/A

### Expected Behaviour

N/A

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/86980013/4b281528-151c-4254-ba38-f06eed934afd)

### `/qs paste` URL

https://paste.helpch.at/ikofuhajel.less

**Comment by Ghost-chu** [comment]
The version of MySQL database you are running is not supported by QuickShop-Hikari.

Recommended MySQL version: MySQL 8+
Official supported lowest MySQL version: MySQL 5.7+

You should upgrade your MySQL database up to (at least) MySQL 5.7+.

---

If you are not able to upgrading the database version, you can use the built-in H2 database.

**Comment by 164ebr** [comment]
thank you..
