### ISSUE TITLE
[BUG] When Shop in Residence and player not build permissions, click sign not work.

### ISSUE THREAD

**Issue by addpromax** [Ghost-chu/QuickShop-Hikari#998]
### Description

When Shop in Residence and player not build permissions, click sign not work.
click sign will give a tip:
You have not build permissions

### Steps to reproduce

1.Use Residence 5.1.2.1 and quickshop 4.2.2.12
2.Use Residence create protect. Not give build permissions
3.Residence give a tip : You have not build permissions
4.**click chest is work**

### Expected Behaviour

Click chest is work to buy something

### Screenshots

![微信图片_20230725094446](https://github.com/Ghost-chu/QuickShop-Hikari/assets/124496967/54dc3fd9-cd41-4bfb-bf7f-064f7237cfb0)

### `/qs paste` URL

http://www.vtbmc.cc/paste-8af4ea10c72142f2ae5198e7b18fdaf8.html

**Comment by Ghost-chu** [comment]
https://github.com/Zrips/Residence/issues/1064


It has been fixed in latest Residence
